Started GET "/" for ::1 at 2019-03-19 17:10:47 -0700
  
Mysql2::Error::ConnectionError (Access denied for user 'root'@'localhost' (using password: YES)):
  
mysql2-0.5.2-x86 (mingw32) lib/mysql2/client.rb:90:in `connect'
mysql2-0.5.2-x86 (mingw32) lib/mysql2/client.rb:90:in `initialize'
activerecord (5.0.7.2) lib/active_record/connection_adapters/mysql2_adapter.rb:25:in `new'
activerecord (5.0.7.2) lib/active_record/connection_adapters/mysql2_adapter.rb:25:in `mysql2_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:729:in `new_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:773:in `checkout_new_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:752:in `try_to_checkout_new_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:713:in `acquire_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:490:in `checkout'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:364:in `connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:883:in `retrieve_connection'
activerecord (5.0.7.2) lib/active_record/connection_handling.rb:128:in `retrieve_connection'
activerecord (5.0.7.2) lib/active_record/connection_handling.rb:91:in `connection'
activerecord (5.0.7.2) lib/active_record/migration.rb:559:in `connection'
activerecord (5.0.7.2) lib/active_record/migration.rb:546:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:97:in `__run_callbacks__'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:90:in `run_callbacks'
actionpack (5.0.7.2) lib/action_dispatch/middleware/callbacks.rb:36:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.0.7.2) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.0.7.2) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.0.7.2) lib/rails/rack/logger.rb:24:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/request_id.rb:24:in `call'
rack (2.0.6) lib/rack/runtime.rb:22:in `call'
activesupport (5.0.7.2) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/static.rb:136:in `call'
rack (2.0.6) lib/rack/sendfile.rb:111:in `call'
railties (5.0.7.2) lib/rails/engine.rb:522:in `call'
puma (3.12.1) lib/puma/configuration.rb:227:in `call'
puma (3.12.1) lib/puma/server.rb:660:in `handle_request'
puma (3.12.1) lib/puma/server.rb:474:in `process_client'
puma (3.12.1) lib/puma/server.rb:334:in `block in run'
puma (3.12.1) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Started GET "/favicon.ico" for ::1 at 2019-03-19 17:10:49 -0700
  
Mysql2::Error::ConnectionError (Access denied for user 'root'@'localhost' (using password: YES)):
  
mysql2-0.5.2-x86 (mingw32) lib/mysql2/client.rb:90:in `connect'
mysql2-0.5.2-x86 (mingw32) lib/mysql2/client.rb:90:in `initialize'
activerecord (5.0.7.2) lib/active_record/connection_adapters/mysql2_adapter.rb:25:in `new'
activerecord (5.0.7.2) lib/active_record/connection_adapters/mysql2_adapter.rb:25:in `mysql2_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:729:in `new_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:773:in `checkout_new_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:752:in `try_to_checkout_new_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:713:in `acquire_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:490:in `checkout'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:364:in `connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:883:in `retrieve_connection'
activerecord (5.0.7.2) lib/active_record/connection_handling.rb:128:in `retrieve_connection'
activerecord (5.0.7.2) lib/active_record/connection_handling.rb:91:in `connection'
activerecord (5.0.7.2) lib/active_record/migration.rb:559:in `connection'
activerecord (5.0.7.2) lib/active_record/migration.rb:546:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:97:in `__run_callbacks__'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:90:in `run_callbacks'
actionpack (5.0.7.2) lib/action_dispatch/middleware/callbacks.rb:36:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.0.7.2) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.0.7.2) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.0.7.2) lib/rails/rack/logger.rb:24:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/request_id.rb:24:in `call'
rack (2.0.6) lib/rack/runtime.rb:22:in `call'
activesupport (5.0.7.2) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/static.rb:136:in `call'
rack (2.0.6) lib/rack/sendfile.rb:111:in `call'
railties (5.0.7.2) lib/rails/engine.rb:522:in `call'
puma (3.12.1) lib/puma/configuration.rb:227:in `call'
puma (3.12.1) lib/puma/server.rb:660:in `handle_request'
puma (3.12.1) lib/puma/server.rb:474:in `process_client'
puma (3.12.1) lib/puma/server.rb:334:in `block in run'
puma (3.12.1) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Started GET "/" for ::1 at 2019-03-19 17:13:34 -0700
  
Mysql2::Error::ConnectionError (Access denied for user 'root'@'localhost' (using password: YES)):
  
mysql2-0.5.2-x86 (mingw32) lib/mysql2/client.rb:90:in `connect'
mysql2-0.5.2-x86 (mingw32) lib/mysql2/client.rb:90:in `initialize'
activerecord (5.0.7.2) lib/active_record/connection_adapters/mysql2_adapter.rb:25:in `new'
activerecord (5.0.7.2) lib/active_record/connection_adapters/mysql2_adapter.rb:25:in `mysql2_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:729:in `new_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:773:in `checkout_new_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:752:in `try_to_checkout_new_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:713:in `acquire_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:490:in `checkout'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:364:in `connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:883:in `retrieve_connection'
activerecord (5.0.7.2) lib/active_record/connection_handling.rb:128:in `retrieve_connection'
activerecord (5.0.7.2) lib/active_record/connection_handling.rb:91:in `connection'
activerecord (5.0.7.2) lib/active_record/migration.rb:559:in `connection'
activerecord (5.0.7.2) lib/active_record/migration.rb:546:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:97:in `__run_callbacks__'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:90:in `run_callbacks'
actionpack (5.0.7.2) lib/action_dispatch/middleware/callbacks.rb:36:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.0.7.2) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.0.7.2) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.0.7.2) lib/rails/rack/logger.rb:24:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/request_id.rb:24:in `call'
rack (2.0.6) lib/rack/runtime.rb:22:in `call'
activesupport (5.0.7.2) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/static.rb:136:in `call'
rack (2.0.6) lib/rack/sendfile.rb:111:in `call'
railties (5.0.7.2) lib/rails/engine.rb:522:in `call'
puma (3.12.1) lib/puma/configuration.rb:227:in `call'
puma (3.12.1) lib/puma/server.rb:660:in `handle_request'
puma (3.12.1) lib/puma/server.rb:474:in `process_client'
puma (3.12.1) lib/puma/server.rb:334:in `block in run'
puma (3.12.1) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Started GET "/favicon.ico" for ::1 at 2019-03-19 17:13:35 -0700
  
Mysql2::Error::ConnectionError (Access denied for user 'root'@'localhost' (using password: YES)):
  
mysql2-0.5.2-x86 (mingw32) lib/mysql2/client.rb:90:in `connect'
mysql2-0.5.2-x86 (mingw32) lib/mysql2/client.rb:90:in `initialize'
activerecord (5.0.7.2) lib/active_record/connection_adapters/mysql2_adapter.rb:25:in `new'
activerecord (5.0.7.2) lib/active_record/connection_adapters/mysql2_adapter.rb:25:in `mysql2_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:729:in `new_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:773:in `checkout_new_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:752:in `try_to_checkout_new_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:713:in `acquire_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:490:in `checkout'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:364:in `connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:883:in `retrieve_connection'
activerecord (5.0.7.2) lib/active_record/connection_handling.rb:128:in `retrieve_connection'
activerecord (5.0.7.2) lib/active_record/connection_handling.rb:91:in `connection'
activerecord (5.0.7.2) lib/active_record/migration.rb:559:in `connection'
activerecord (5.0.7.2) lib/active_record/migration.rb:546:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:97:in `__run_callbacks__'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:90:in `run_callbacks'
actionpack (5.0.7.2) lib/action_dispatch/middleware/callbacks.rb:36:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.0.7.2) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.0.7.2) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.0.7.2) lib/rails/rack/logger.rb:24:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/request_id.rb:24:in `call'
rack (2.0.6) lib/rack/runtime.rb:22:in `call'
activesupport (5.0.7.2) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/static.rb:136:in `call'
rack (2.0.6) lib/rack/sendfile.rb:111:in `call'
railties (5.0.7.2) lib/rails/engine.rb:522:in `call'
puma (3.12.1) lib/puma/configuration.rb:227:in `call'
puma (3.12.1) lib/puma/server.rb:660:in `handle_request'
puma (3.12.1) lib/puma/server.rb:474:in `process_client'
puma (3.12.1) lib/puma/server.rb:334:in `block in run'
puma (3.12.1) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Started GET "/" for ::1 at 2019-03-19 17:13:42 -0700
  
Mysql2::Error::ConnectionError (Access denied for user 'root'@'localhost' (using password: YES)):
  
mysql2-0.5.2-x86 (mingw32) lib/mysql2/client.rb:90:in `connect'
mysql2-0.5.2-x86 (mingw32) lib/mysql2/client.rb:90:in `initialize'
activerecord (5.0.7.2) lib/active_record/connection_adapters/mysql2_adapter.rb:25:in `new'
activerecord (5.0.7.2) lib/active_record/connection_adapters/mysql2_adapter.rb:25:in `mysql2_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:729:in `new_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:773:in `checkout_new_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:752:in `try_to_checkout_new_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:713:in `acquire_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:490:in `checkout'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:364:in `connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:883:in `retrieve_connection'
activerecord (5.0.7.2) lib/active_record/connection_handling.rb:128:in `retrieve_connection'
activerecord (5.0.7.2) lib/active_record/connection_handling.rb:91:in `connection'
activerecord (5.0.7.2) lib/active_record/migration.rb:559:in `connection'
activerecord (5.0.7.2) lib/active_record/migration.rb:546:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:97:in `__run_callbacks__'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:90:in `run_callbacks'
actionpack (5.0.7.2) lib/action_dispatch/middleware/callbacks.rb:36:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.0.7.2) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.0.7.2) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.0.7.2) lib/rails/rack/logger.rb:24:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/request_id.rb:24:in `call'
rack (2.0.6) lib/rack/runtime.rb:22:in `call'
activesupport (5.0.7.2) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/static.rb:136:in `call'
rack (2.0.6) lib/rack/sendfile.rb:111:in `call'
railties (5.0.7.2) lib/rails/engine.rb:522:in `call'
puma (3.12.1) lib/puma/configuration.rb:227:in `call'
puma (3.12.1) lib/puma/server.rb:660:in `handle_request'
puma (3.12.1) lib/puma/server.rb:474:in `process_client'
puma (3.12.1) lib/puma/server.rb:334:in `block in run'
puma (3.12.1) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Started GET "/favicon.ico" for ::1 at 2019-03-19 17:13:43 -0700
  
Mysql2::Error::ConnectionError (Access denied for user 'root'@'localhost' (using password: YES)):
  
mysql2-0.5.2-x86 (mingw32) lib/mysql2/client.rb:90:in `connect'
mysql2-0.5.2-x86 (mingw32) lib/mysql2/client.rb:90:in `initialize'
activerecord (5.0.7.2) lib/active_record/connection_adapters/mysql2_adapter.rb:25:in `new'
activerecord (5.0.7.2) lib/active_record/connection_adapters/mysql2_adapter.rb:25:in `mysql2_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:729:in `new_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:773:in `checkout_new_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:752:in `try_to_checkout_new_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:713:in `acquire_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:490:in `checkout'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:364:in `connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:883:in `retrieve_connection'
activerecord (5.0.7.2) lib/active_record/connection_handling.rb:128:in `retrieve_connection'
activerecord (5.0.7.2) lib/active_record/connection_handling.rb:91:in `connection'
activerecord (5.0.7.2) lib/active_record/migration.rb:559:in `connection'
activerecord (5.0.7.2) lib/active_record/migration.rb:546:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:97:in `__run_callbacks__'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:90:in `run_callbacks'
actionpack (5.0.7.2) lib/action_dispatch/middleware/callbacks.rb:36:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.0.7.2) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.0.7.2) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.0.7.2) lib/rails/rack/logger.rb:24:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/request_id.rb:24:in `call'
rack (2.0.6) lib/rack/runtime.rb:22:in `call'
activesupport (5.0.7.2) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/static.rb:136:in `call'
rack (2.0.6) lib/rack/sendfile.rb:111:in `call'
railties (5.0.7.2) lib/rails/engine.rb:522:in `call'
puma (3.12.1) lib/puma/configuration.rb:227:in `call'
puma (3.12.1) lib/puma/server.rb:660:in `handle_request'
puma (3.12.1) lib/puma/server.rb:474:in `process_client'
puma (3.12.1) lib/puma/server.rb:334:in `block in run'
puma (3.12.1) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Started GET "/" for ::1 at 2019-03-19 17:14:39 -0700
  
Mysql2::Error::ConnectionError (Access denied for user 'root'@'localhost' (using password: YES)):
  
mysql2-0.5.2-x86 (mingw32) lib/mysql2/client.rb:90:in `connect'
mysql2-0.5.2-x86 (mingw32) lib/mysql2/client.rb:90:in `initialize'
activerecord (5.0.7.2) lib/active_record/connection_adapters/mysql2_adapter.rb:25:in `new'
activerecord (5.0.7.2) lib/active_record/connection_adapters/mysql2_adapter.rb:25:in `mysql2_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:729:in `new_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:773:in `checkout_new_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:752:in `try_to_checkout_new_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:713:in `acquire_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:490:in `checkout'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:364:in `connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:883:in `retrieve_connection'
activerecord (5.0.7.2) lib/active_record/connection_handling.rb:128:in `retrieve_connection'
activerecord (5.0.7.2) lib/active_record/connection_handling.rb:91:in `connection'
activerecord (5.0.7.2) lib/active_record/migration.rb:559:in `connection'
activerecord (5.0.7.2) lib/active_record/migration.rb:546:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:97:in `__run_callbacks__'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:90:in `run_callbacks'
actionpack (5.0.7.2) lib/action_dispatch/middleware/callbacks.rb:36:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.0.7.2) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.0.7.2) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.0.7.2) lib/rails/rack/logger.rb:24:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/request_id.rb:24:in `call'
rack (2.0.6) lib/rack/runtime.rb:22:in `call'
activesupport (5.0.7.2) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/static.rb:136:in `call'
rack (2.0.6) lib/rack/sendfile.rb:111:in `call'
railties (5.0.7.2) lib/rails/engine.rb:522:in `call'
puma (3.12.1) lib/puma/configuration.rb:227:in `call'
puma (3.12.1) lib/puma/server.rb:660:in `handle_request'
puma (3.12.1) lib/puma/server.rb:474:in `process_client'
puma (3.12.1) lib/puma/server.rb:334:in `block in run'
puma (3.12.1) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Started GET "/favicon.ico" for ::1 at 2019-03-19 17:14:41 -0700
  
Mysql2::Error::ConnectionError (Access denied for user 'root'@'localhost' (using password: YES)):
  
mysql2-0.5.2-x86 (mingw32) lib/mysql2/client.rb:90:in `connect'
mysql2-0.5.2-x86 (mingw32) lib/mysql2/client.rb:90:in `initialize'
activerecord (5.0.7.2) lib/active_record/connection_adapters/mysql2_adapter.rb:25:in `new'
activerecord (5.0.7.2) lib/active_record/connection_adapters/mysql2_adapter.rb:25:in `mysql2_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:729:in `new_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:773:in `checkout_new_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:752:in `try_to_checkout_new_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:713:in `acquire_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:490:in `checkout'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:364:in `connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:883:in `retrieve_connection'
activerecord (5.0.7.2) lib/active_record/connection_handling.rb:128:in `retrieve_connection'
activerecord (5.0.7.2) lib/active_record/connection_handling.rb:91:in `connection'
activerecord (5.0.7.2) lib/active_record/migration.rb:559:in `connection'
activerecord (5.0.7.2) lib/active_record/migration.rb:546:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:97:in `__run_callbacks__'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:90:in `run_callbacks'
actionpack (5.0.7.2) lib/action_dispatch/middleware/callbacks.rb:36:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.0.7.2) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.0.7.2) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.0.7.2) lib/rails/rack/logger.rb:24:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/request_id.rb:24:in `call'
rack (2.0.6) lib/rack/runtime.rb:22:in `call'
activesupport (5.0.7.2) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/static.rb:136:in `call'
rack (2.0.6) lib/rack/sendfile.rb:111:in `call'
railties (5.0.7.2) lib/rails/engine.rb:522:in `call'
puma (3.12.1) lib/puma/configuration.rb:227:in `call'
puma (3.12.1) lib/puma/server.rb:660:in `handle_request'
puma (3.12.1) lib/puma/server.rb:474:in `process_client'
puma (3.12.1) lib/puma/server.rb:334:in `block in run'
puma (3.12.1) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Started GET "/" for ::1 at 2019-03-19 17:30:12 -0700
  
Mysql2::Error::ConnectionError (Access denied for user 'root'@'localhost' (using password: YES)):
  
mysql2-0.5.2-x86 (mingw32) lib/mysql2/client.rb:90:in `connect'
mysql2-0.5.2-x86 (mingw32) lib/mysql2/client.rb:90:in `initialize'
activerecord (5.0.7.2) lib/active_record/connection_adapters/mysql2_adapter.rb:25:in `new'
activerecord (5.0.7.2) lib/active_record/connection_adapters/mysql2_adapter.rb:25:in `mysql2_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:729:in `new_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:773:in `checkout_new_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:752:in `try_to_checkout_new_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:713:in `acquire_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:490:in `checkout'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:364:in `connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:883:in `retrieve_connection'
activerecord (5.0.7.2) lib/active_record/connection_handling.rb:128:in `retrieve_connection'
activerecord (5.0.7.2) lib/active_record/connection_handling.rb:91:in `connection'
activerecord (5.0.7.2) lib/active_record/migration.rb:559:in `connection'
activerecord (5.0.7.2) lib/active_record/migration.rb:546:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:97:in `__run_callbacks__'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:90:in `run_callbacks'
actionpack (5.0.7.2) lib/action_dispatch/middleware/callbacks.rb:36:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.0.7.2) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.0.7.2) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.0.7.2) lib/rails/rack/logger.rb:24:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/request_id.rb:24:in `call'
rack (2.0.6) lib/rack/runtime.rb:22:in `call'
activesupport (5.0.7.2) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/static.rb:136:in `call'
rack (2.0.6) lib/rack/sendfile.rb:111:in `call'
railties (5.0.7.2) lib/rails/engine.rb:522:in `call'
puma (3.12.1) lib/puma/configuration.rb:227:in `call'
puma (3.12.1) lib/puma/server.rb:660:in `handle_request'
puma (3.12.1) lib/puma/server.rb:474:in `process_client'
puma (3.12.1) lib/puma/server.rb:334:in `block in run'
puma (3.12.1) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Started GET "/favicon.ico" for ::1 at 2019-03-19 17:30:14 -0700
  
Mysql2::Error::ConnectionError (Access denied for user 'root'@'localhost' (using password: YES)):
  
mysql2-0.5.2-x86 (mingw32) lib/mysql2/client.rb:90:in `connect'
mysql2-0.5.2-x86 (mingw32) lib/mysql2/client.rb:90:in `initialize'
activerecord (5.0.7.2) lib/active_record/connection_adapters/mysql2_adapter.rb:25:in `new'
activerecord (5.0.7.2) lib/active_record/connection_adapters/mysql2_adapter.rb:25:in `mysql2_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:729:in `new_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:773:in `checkout_new_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:752:in `try_to_checkout_new_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:713:in `acquire_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:490:in `checkout'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:364:in `connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:883:in `retrieve_connection'
activerecord (5.0.7.2) lib/active_record/connection_handling.rb:128:in `retrieve_connection'
activerecord (5.0.7.2) lib/active_record/connection_handling.rb:91:in `connection'
activerecord (5.0.7.2) lib/active_record/migration.rb:559:in `connection'
activerecord (5.0.7.2) lib/active_record/migration.rb:546:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:97:in `__run_callbacks__'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:90:in `run_callbacks'
actionpack (5.0.7.2) lib/action_dispatch/middleware/callbacks.rb:36:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.0.7.2) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.0.7.2) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.0.7.2) lib/rails/rack/logger.rb:24:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/request_id.rb:24:in `call'
rack (2.0.6) lib/rack/runtime.rb:22:in `call'
activesupport (5.0.7.2) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/static.rb:136:in `call'
rack (2.0.6) lib/rack/sendfile.rb:111:in `call'
railties (5.0.7.2) lib/rails/engine.rb:522:in `call'
puma (3.12.1) lib/puma/configuration.rb:227:in `call'
puma (3.12.1) lib/puma/server.rb:660:in `handle_request'
puma (3.12.1) lib/puma/server.rb:474:in `process_client'
puma (3.12.1) lib/puma/server.rb:334:in `block in run'
puma (3.12.1) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Started GET "/" for ::1 at 2019-03-19 17:40:43 -0700
  
Mysql2::Error::ConnectionError (Access denied for user 'root'@'localhost' (using password: YES)):
  
mysql2-0.5.2-x86 (mingw32) lib/mysql2/client.rb:90:in `connect'
mysql2-0.5.2-x86 (mingw32) lib/mysql2/client.rb:90:in `initialize'
activerecord (5.0.7.2) lib/active_record/connection_adapters/mysql2_adapter.rb:25:in `new'
activerecord (5.0.7.2) lib/active_record/connection_adapters/mysql2_adapter.rb:25:in `mysql2_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:729:in `new_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:773:in `checkout_new_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:752:in `try_to_checkout_new_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:713:in `acquire_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:490:in `checkout'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:364:in `connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:883:in `retrieve_connection'
activerecord (5.0.7.2) lib/active_record/connection_handling.rb:128:in `retrieve_connection'
activerecord (5.0.7.2) lib/active_record/connection_handling.rb:91:in `connection'
activerecord (5.0.7.2) lib/active_record/migration.rb:559:in `connection'
activerecord (5.0.7.2) lib/active_record/migration.rb:546:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:97:in `__run_callbacks__'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:90:in `run_callbacks'
actionpack (5.0.7.2) lib/action_dispatch/middleware/callbacks.rb:36:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.0.7.2) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.0.7.2) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.0.7.2) lib/rails/rack/logger.rb:24:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/request_id.rb:24:in `call'
rack (2.0.6) lib/rack/runtime.rb:22:in `call'
activesupport (5.0.7.2) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/static.rb:136:in `call'
rack (2.0.6) lib/rack/sendfile.rb:111:in `call'
railties (5.0.7.2) lib/rails/engine.rb:522:in `call'
puma (3.12.1) lib/puma/configuration.rb:227:in `call'
puma (3.12.1) lib/puma/server.rb:660:in `handle_request'
puma (3.12.1) lib/puma/server.rb:474:in `process_client'
puma (3.12.1) lib/puma/server.rb:334:in `block in run'
puma (3.12.1) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Started GET "/favicon.ico" for ::1 at 2019-03-19 17:40:45 -0700
  
Mysql2::Error::ConnectionError (Access denied for user 'root'@'localhost' (using password: YES)):
  
mysql2-0.5.2-x86 (mingw32) lib/mysql2/client.rb:90:in `connect'
mysql2-0.5.2-x86 (mingw32) lib/mysql2/client.rb:90:in `initialize'
activerecord (5.0.7.2) lib/active_record/connection_adapters/mysql2_adapter.rb:25:in `new'
activerecord (5.0.7.2) lib/active_record/connection_adapters/mysql2_adapter.rb:25:in `mysql2_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:729:in `new_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:773:in `checkout_new_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:752:in `try_to_checkout_new_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:713:in `acquire_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:490:in `checkout'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:364:in `connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:883:in `retrieve_connection'
activerecord (5.0.7.2) lib/active_record/connection_handling.rb:128:in `retrieve_connection'
activerecord (5.0.7.2) lib/active_record/connection_handling.rb:91:in `connection'
activerecord (5.0.7.2) lib/active_record/migration.rb:559:in `connection'
activerecord (5.0.7.2) lib/active_record/migration.rb:546:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:97:in `__run_callbacks__'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:90:in `run_callbacks'
actionpack (5.0.7.2) lib/action_dispatch/middleware/callbacks.rb:36:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.0.7.2) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.0.7.2) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.0.7.2) lib/rails/rack/logger.rb:24:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/request_id.rb:24:in `call'
rack (2.0.6) lib/rack/runtime.rb:22:in `call'
activesupport (5.0.7.2) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/static.rb:136:in `call'
rack (2.0.6) lib/rack/sendfile.rb:111:in `call'
railties (5.0.7.2) lib/rails/engine.rb:522:in `call'
puma (3.12.1) lib/puma/configuration.rb:227:in `call'
puma (3.12.1) lib/puma/server.rb:660:in `handle_request'
puma (3.12.1) lib/puma/server.rb:474:in `process_client'
puma (3.12.1) lib/puma/server.rb:334:in `block in run'
puma (3.12.1) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Started GET "/" for ::1 at 2019-03-19 17:44:39 -0700
  
Mysql2::Error::ConnectionError (Access denied for user 'alekh'@'localhost' (using password: YES)):
  
mysql2-0.5.2-x86 (mingw32) lib/mysql2/client.rb:90:in `connect'
mysql2-0.5.2-x86 (mingw32) lib/mysql2/client.rb:90:in `initialize'
activerecord (5.0.7.2) lib/active_record/connection_adapters/mysql2_adapter.rb:25:in `new'
activerecord (5.0.7.2) lib/active_record/connection_adapters/mysql2_adapter.rb:25:in `mysql2_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:729:in `new_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:773:in `checkout_new_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:752:in `try_to_checkout_new_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:713:in `acquire_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:490:in `checkout'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:364:in `connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:883:in `retrieve_connection'
activerecord (5.0.7.2) lib/active_record/connection_handling.rb:128:in `retrieve_connection'
activerecord (5.0.7.2) lib/active_record/connection_handling.rb:91:in `connection'
activerecord (5.0.7.2) lib/active_record/migration.rb:559:in `connection'
activerecord (5.0.7.2) lib/active_record/migration.rb:546:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:97:in `__run_callbacks__'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:90:in `run_callbacks'
actionpack (5.0.7.2) lib/action_dispatch/middleware/callbacks.rb:36:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.0.7.2) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.0.7.2) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.0.7.2) lib/rails/rack/logger.rb:24:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/request_id.rb:24:in `call'
rack (2.0.6) lib/rack/runtime.rb:22:in `call'
activesupport (5.0.7.2) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/static.rb:136:in `call'
rack (2.0.6) lib/rack/sendfile.rb:111:in `call'
railties (5.0.7.2) lib/rails/engine.rb:522:in `call'
puma (3.12.1) lib/puma/configuration.rb:227:in `call'
puma (3.12.1) lib/puma/server.rb:660:in `handle_request'
puma (3.12.1) lib/puma/server.rb:474:in `process_client'
puma (3.12.1) lib/puma/server.rb:334:in `block in run'
puma (3.12.1) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Started GET "/favicon.ico" for ::1 at 2019-03-19 17:44:41 -0700
  
Mysql2::Error::ConnectionError (Access denied for user 'alekh'@'localhost' (using password: YES)):
  
mysql2-0.5.2-x86 (mingw32) lib/mysql2/client.rb:90:in `connect'
mysql2-0.5.2-x86 (mingw32) lib/mysql2/client.rb:90:in `initialize'
activerecord (5.0.7.2) lib/active_record/connection_adapters/mysql2_adapter.rb:25:in `new'
activerecord (5.0.7.2) lib/active_record/connection_adapters/mysql2_adapter.rb:25:in `mysql2_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:729:in `new_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:773:in `checkout_new_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:752:in `try_to_checkout_new_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:713:in `acquire_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:490:in `checkout'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:364:in `connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:883:in `retrieve_connection'
activerecord (5.0.7.2) lib/active_record/connection_handling.rb:128:in `retrieve_connection'
activerecord (5.0.7.2) lib/active_record/connection_handling.rb:91:in `connection'
activerecord (5.0.7.2) lib/active_record/migration.rb:559:in `connection'
activerecord (5.0.7.2) lib/active_record/migration.rb:546:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:97:in `__run_callbacks__'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:90:in `run_callbacks'
actionpack (5.0.7.2) lib/action_dispatch/middleware/callbacks.rb:36:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.0.7.2) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.0.7.2) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.0.7.2) lib/rails/rack/logger.rb:24:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/request_id.rb:24:in `call'
rack (2.0.6) lib/rack/runtime.rb:22:in `call'
activesupport (5.0.7.2) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/static.rb:136:in `call'
rack (2.0.6) lib/rack/sendfile.rb:111:in `call'
railties (5.0.7.2) lib/rails/engine.rb:522:in `call'
puma (3.12.1) lib/puma/configuration.rb:227:in `call'
puma (3.12.1) lib/puma/server.rb:660:in `handle_request'
puma (3.12.1) lib/puma/server.rb:474:in `process_client'
puma (3.12.1) lib/puma/server.rb:334:in `block in run'
puma (3.12.1) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Started GET "/" for ::1 at 2019-03-19 17:49:07 -0700
  
Mysql2::Error::ConnectionError (Access denied for user 'alekh'@'localhost' (using password: YES)):
  
mysql2-0.5.2-x86 (mingw32) lib/mysql2/client.rb:90:in `connect'
mysql2-0.5.2-x86 (mingw32) lib/mysql2/client.rb:90:in `initialize'
activerecord (5.0.7.2) lib/active_record/connection_adapters/mysql2_adapter.rb:25:in `new'
activerecord (5.0.7.2) lib/active_record/connection_adapters/mysql2_adapter.rb:25:in `mysql2_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:729:in `new_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:773:in `checkout_new_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:752:in `try_to_checkout_new_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:713:in `acquire_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:490:in `checkout'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:364:in `connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:883:in `retrieve_connection'
activerecord (5.0.7.2) lib/active_record/connection_handling.rb:128:in `retrieve_connection'
activerecord (5.0.7.2) lib/active_record/connection_handling.rb:91:in `connection'
activerecord (5.0.7.2) lib/active_record/migration.rb:559:in `connection'
activerecord (5.0.7.2) lib/active_record/migration.rb:546:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:97:in `__run_callbacks__'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:90:in `run_callbacks'
actionpack (5.0.7.2) lib/action_dispatch/middleware/callbacks.rb:36:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.0.7.2) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.0.7.2) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.0.7.2) lib/rails/rack/logger.rb:24:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/request_id.rb:24:in `call'
rack (2.0.6) lib/rack/runtime.rb:22:in `call'
activesupport (5.0.7.2) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/static.rb:136:in `call'
rack (2.0.6) lib/rack/sendfile.rb:111:in `call'
railties (5.0.7.2) lib/rails/engine.rb:522:in `call'
puma (3.12.1) lib/puma/configuration.rb:227:in `call'
puma (3.12.1) lib/puma/server.rb:660:in `handle_request'
puma (3.12.1) lib/puma/server.rb:474:in `process_client'
puma (3.12.1) lib/puma/server.rb:334:in `block in run'
puma (3.12.1) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Started GET "/favicon.ico" for ::1 at 2019-03-19 17:49:09 -0700
  
Mysql2::Error::ConnectionError (Access denied for user 'alekh'@'localhost' (using password: YES)):
  
mysql2-0.5.2-x86 (mingw32) lib/mysql2/client.rb:90:in `connect'
mysql2-0.5.2-x86 (mingw32) lib/mysql2/client.rb:90:in `initialize'
activerecord (5.0.7.2) lib/active_record/connection_adapters/mysql2_adapter.rb:25:in `new'
activerecord (5.0.7.2) lib/active_record/connection_adapters/mysql2_adapter.rb:25:in `mysql2_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:729:in `new_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:773:in `checkout_new_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:752:in `try_to_checkout_new_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:713:in `acquire_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:490:in `checkout'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:364:in `connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:883:in `retrieve_connection'
activerecord (5.0.7.2) lib/active_record/connection_handling.rb:128:in `retrieve_connection'
activerecord (5.0.7.2) lib/active_record/connection_handling.rb:91:in `connection'
activerecord (5.0.7.2) lib/active_record/migration.rb:559:in `connection'
activerecord (5.0.7.2) lib/active_record/migration.rb:546:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:97:in `__run_callbacks__'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:90:in `run_callbacks'
actionpack (5.0.7.2) lib/action_dispatch/middleware/callbacks.rb:36:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.0.7.2) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.0.7.2) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.0.7.2) lib/rails/rack/logger.rb:24:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/request_id.rb:24:in `call'
rack (2.0.6) lib/rack/runtime.rb:22:in `call'
activesupport (5.0.7.2) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/static.rb:136:in `call'
rack (2.0.6) lib/rack/sendfile.rb:111:in `call'
railties (5.0.7.2) lib/rails/engine.rb:522:in `call'
puma (3.12.1) lib/puma/configuration.rb:227:in `call'
puma (3.12.1) lib/puma/server.rb:660:in `handle_request'
puma (3.12.1) lib/puma/server.rb:474:in `process_client'
puma (3.12.1) lib/puma/server.rb:334:in `block in run'
puma (3.12.1) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Started GET "/" for ::1 at 2019-03-19 17:51:38 -0700
  
Mysql2::Error::ConnectionError (Access denied for user ''@'localhost' to database 'organizationalevents'):
  
mysql2-0.5.2-x86 (mingw32) lib/mysql2/client.rb:90:in `connect'
mysql2-0.5.2-x86 (mingw32) lib/mysql2/client.rb:90:in `initialize'
activerecord (5.0.7.2) lib/active_record/connection_adapters/mysql2_adapter.rb:25:in `new'
activerecord (5.0.7.2) lib/active_record/connection_adapters/mysql2_adapter.rb:25:in `mysql2_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:729:in `new_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:773:in `checkout_new_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:752:in `try_to_checkout_new_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:713:in `acquire_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:490:in `checkout'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:364:in `connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:883:in `retrieve_connection'
activerecord (5.0.7.2) lib/active_record/connection_handling.rb:128:in `retrieve_connection'
activerecord (5.0.7.2) lib/active_record/connection_handling.rb:91:in `connection'
activerecord (5.0.7.2) lib/active_record/migration.rb:559:in `connection'
activerecord (5.0.7.2) lib/active_record/migration.rb:546:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:97:in `__run_callbacks__'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:90:in `run_callbacks'
actionpack (5.0.7.2) lib/action_dispatch/middleware/callbacks.rb:36:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.0.7.2) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.0.7.2) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.0.7.2) lib/rails/rack/logger.rb:24:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/request_id.rb:24:in `call'
rack (2.0.6) lib/rack/runtime.rb:22:in `call'
activesupport (5.0.7.2) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/static.rb:136:in `call'
rack (2.0.6) lib/rack/sendfile.rb:111:in `call'
railties (5.0.7.2) lib/rails/engine.rb:522:in `call'
puma (3.12.1) lib/puma/configuration.rb:227:in `call'
puma (3.12.1) lib/puma/server.rb:660:in `handle_request'
puma (3.12.1) lib/puma/server.rb:474:in `process_client'
puma (3.12.1) lib/puma/server.rb:334:in `block in run'
puma (3.12.1) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Started GET "/favicon.ico" for ::1 at 2019-03-19 17:51:39 -0700
  
Mysql2::Error::ConnectionError (Access denied for user ''@'localhost' to database 'organizationalevents'):
  
mysql2-0.5.2-x86 (mingw32) lib/mysql2/client.rb:90:in `connect'
mysql2-0.5.2-x86 (mingw32) lib/mysql2/client.rb:90:in `initialize'
activerecord (5.0.7.2) lib/active_record/connection_adapters/mysql2_adapter.rb:25:in `new'
activerecord (5.0.7.2) lib/active_record/connection_adapters/mysql2_adapter.rb:25:in `mysql2_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:729:in `new_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:773:in `checkout_new_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:752:in `try_to_checkout_new_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:713:in `acquire_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:490:in `checkout'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:364:in `connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:883:in `retrieve_connection'
activerecord (5.0.7.2) lib/active_record/connection_handling.rb:128:in `retrieve_connection'
activerecord (5.0.7.2) lib/active_record/connection_handling.rb:91:in `connection'
activerecord (5.0.7.2) lib/active_record/migration.rb:559:in `connection'
activerecord (5.0.7.2) lib/active_record/migration.rb:546:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:97:in `__run_callbacks__'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:90:in `run_callbacks'
actionpack (5.0.7.2) lib/action_dispatch/middleware/callbacks.rb:36:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.0.7.2) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.0.7.2) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.0.7.2) lib/rails/rack/logger.rb:24:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/request_id.rb:24:in `call'
rack (2.0.6) lib/rack/runtime.rb:22:in `call'
activesupport (5.0.7.2) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/static.rb:136:in `call'
rack (2.0.6) lib/rack/sendfile.rb:111:in `call'
railties (5.0.7.2) lib/rails/engine.rb:522:in `call'
puma (3.12.1) lib/puma/configuration.rb:227:in `call'
puma (3.12.1) lib/puma/server.rb:660:in `handle_request'
puma (3.12.1) lib/puma/server.rb:474:in `process_client'
puma (3.12.1) lib/puma/server.rb:334:in `block in run'
puma (3.12.1) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Started GET "/" for ::1 at 2019-03-19 22:21:51 -0700
  
Mysql2::Error::ConnectionError (Access denied for user 'alekh'@'localhost' (using password: YES)):
  
mysql2-0.5.2-x86 (mingw32) lib/mysql2/client.rb:90:in `connect'
mysql2-0.5.2-x86 (mingw32) lib/mysql2/client.rb:90:in `initialize'
activerecord (5.0.7.2) lib/active_record/connection_adapters/mysql2_adapter.rb:25:in `new'
activerecord (5.0.7.2) lib/active_record/connection_adapters/mysql2_adapter.rb:25:in `mysql2_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:729:in `new_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:773:in `checkout_new_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:752:in `try_to_checkout_new_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:713:in `acquire_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:490:in `checkout'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:364:in `connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:883:in `retrieve_connection'
activerecord (5.0.7.2) lib/active_record/connection_handling.rb:128:in `retrieve_connection'
activerecord (5.0.7.2) lib/active_record/connection_handling.rb:91:in `connection'
activerecord (5.0.7.2) lib/active_record/migration.rb:559:in `connection'
activerecord (5.0.7.2) lib/active_record/migration.rb:546:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:97:in `__run_callbacks__'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:90:in `run_callbacks'
actionpack (5.0.7.2) lib/action_dispatch/middleware/callbacks.rb:36:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.0.7.2) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.0.7.2) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.0.7.2) lib/rails/rack/logger.rb:24:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/request_id.rb:24:in `call'
rack (2.0.6) lib/rack/runtime.rb:22:in `call'
activesupport (5.0.7.2) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/static.rb:136:in `call'
rack (2.0.6) lib/rack/sendfile.rb:111:in `call'
railties (5.0.7.2) lib/rails/engine.rb:522:in `call'
puma (3.12.1) lib/puma/configuration.rb:227:in `call'
puma (3.12.1) lib/puma/server.rb:660:in `handle_request'
puma (3.12.1) lib/puma/server.rb:474:in `process_client'
puma (3.12.1) lib/puma/server.rb:334:in `block in run'
puma (3.12.1) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Started GET "/favicon.ico" for ::1 at 2019-03-19 22:21:53 -0700
  
Mysql2::Error::ConnectionError (Access denied for user 'alekh'@'localhost' (using password: YES)):
  
mysql2-0.5.2-x86 (mingw32) lib/mysql2/client.rb:90:in `connect'
mysql2-0.5.2-x86 (mingw32) lib/mysql2/client.rb:90:in `initialize'
activerecord (5.0.7.2) lib/active_record/connection_adapters/mysql2_adapter.rb:25:in `new'
activerecord (5.0.7.2) lib/active_record/connection_adapters/mysql2_adapter.rb:25:in `mysql2_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:729:in `new_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:773:in `checkout_new_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:752:in `try_to_checkout_new_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:713:in `acquire_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:490:in `checkout'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:364:in `connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:883:in `retrieve_connection'
activerecord (5.0.7.2) lib/active_record/connection_handling.rb:128:in `retrieve_connection'
activerecord (5.0.7.2) lib/active_record/connection_handling.rb:91:in `connection'
activerecord (5.0.7.2) lib/active_record/migration.rb:559:in `connection'
activerecord (5.0.7.2) lib/active_record/migration.rb:546:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:97:in `__run_callbacks__'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:90:in `run_callbacks'
actionpack (5.0.7.2) lib/action_dispatch/middleware/callbacks.rb:36:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.0.7.2) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.0.7.2) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.0.7.2) lib/rails/rack/logger.rb:24:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/request_id.rb:24:in `call'
rack (2.0.6) lib/rack/runtime.rb:22:in `call'
activesupport (5.0.7.2) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/static.rb:136:in `call'
rack (2.0.6) lib/rack/sendfile.rb:111:in `call'
railties (5.0.7.2) lib/rails/engine.rb:522:in `call'
puma (3.12.1) lib/puma/configuration.rb:227:in `call'
puma (3.12.1) lib/puma/server.rb:660:in `handle_request'
puma (3.12.1) lib/puma/server.rb:474:in `process_client'
puma (3.12.1) lib/puma/server.rb:334:in `block in run'
puma (3.12.1) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Started GET "/" for ::1 at 2019-03-19 22:32:06 -0700
  
Mysql2::Error::ConnectionError (Access denied for user 'root'@'localhost' (using password: YES)):
  
mysql2-0.5.2-x86 (mingw32) lib/mysql2/client.rb:90:in `connect'
mysql2-0.5.2-x86 (mingw32) lib/mysql2/client.rb:90:in `initialize'
activerecord (5.0.7.2) lib/active_record/connection_adapters/mysql2_adapter.rb:25:in `new'
activerecord (5.0.7.2) lib/active_record/connection_adapters/mysql2_adapter.rb:25:in `mysql2_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:729:in `new_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:773:in `checkout_new_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:752:in `try_to_checkout_new_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:713:in `acquire_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:490:in `checkout'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:364:in `connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:883:in `retrieve_connection'
activerecord (5.0.7.2) lib/active_record/connection_handling.rb:128:in `retrieve_connection'
activerecord (5.0.7.2) lib/active_record/connection_handling.rb:91:in `connection'
activerecord (5.0.7.2) lib/active_record/migration.rb:559:in `connection'
activerecord (5.0.7.2) lib/active_record/migration.rb:546:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:97:in `__run_callbacks__'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:90:in `run_callbacks'
actionpack (5.0.7.2) lib/action_dispatch/middleware/callbacks.rb:36:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.0.7.2) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.0.7.2) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.0.7.2) lib/rails/rack/logger.rb:24:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/request_id.rb:24:in `call'
rack (2.0.6) lib/rack/runtime.rb:22:in `call'
activesupport (5.0.7.2) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/static.rb:136:in `call'
rack (2.0.6) lib/rack/sendfile.rb:111:in `call'
railties (5.0.7.2) lib/rails/engine.rb:522:in `call'
puma (3.12.1) lib/puma/configuration.rb:227:in `call'
puma (3.12.1) lib/puma/server.rb:660:in `handle_request'
puma (3.12.1) lib/puma/server.rb:474:in `process_client'
puma (3.12.1) lib/puma/server.rb:334:in `block in run'
puma (3.12.1) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Started GET "/favicon.ico" for ::1 at 2019-03-19 22:32:08 -0700
  
Mysql2::Error::ConnectionError (Access denied for user 'root'@'localhost' (using password: YES)):
  
mysql2-0.5.2-x86 (mingw32) lib/mysql2/client.rb:90:in `connect'
mysql2-0.5.2-x86 (mingw32) lib/mysql2/client.rb:90:in `initialize'
activerecord (5.0.7.2) lib/active_record/connection_adapters/mysql2_adapter.rb:25:in `new'
activerecord (5.0.7.2) lib/active_record/connection_adapters/mysql2_adapter.rb:25:in `mysql2_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:729:in `new_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:773:in `checkout_new_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:752:in `try_to_checkout_new_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:713:in `acquire_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:490:in `checkout'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:364:in `connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:883:in `retrieve_connection'
activerecord (5.0.7.2) lib/active_record/connection_handling.rb:128:in `retrieve_connection'
activerecord (5.0.7.2) lib/active_record/connection_handling.rb:91:in `connection'
activerecord (5.0.7.2) lib/active_record/migration.rb:559:in `connection'
activerecord (5.0.7.2) lib/active_record/migration.rb:546:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:97:in `__run_callbacks__'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:90:in `run_callbacks'
actionpack (5.0.7.2) lib/action_dispatch/middleware/callbacks.rb:36:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.0.7.2) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.0.7.2) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.0.7.2) lib/rails/rack/logger.rb:24:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/request_id.rb:24:in `call'
rack (2.0.6) lib/rack/runtime.rb:22:in `call'
activesupport (5.0.7.2) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/static.rb:136:in `call'
rack (2.0.6) lib/rack/sendfile.rb:111:in `call'
railties (5.0.7.2) lib/rails/engine.rb:522:in `call'
puma (3.12.1) lib/puma/configuration.rb:227:in `call'
puma (3.12.1) lib/puma/server.rb:660:in `handle_request'
puma (3.12.1) lib/puma/server.rb:474:in `process_client'
puma (3.12.1) lib/puma/server.rb:334:in `block in run'
puma (3.12.1) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Started GET "/" for ::1 at 2019-03-19 22:34:12 -0700
  
Mysql2::Error::ConnectionError (Access denied for user 'root'@'localhost' (using password: YES)):
  
mysql2-0.5.2-x86 (mingw32) lib/mysql2/client.rb:90:in `connect'
mysql2-0.5.2-x86 (mingw32) lib/mysql2/client.rb:90:in `initialize'
activerecord (5.0.7.2) lib/active_record/connection_adapters/mysql2_adapter.rb:25:in `new'
activerecord (5.0.7.2) lib/active_record/connection_adapters/mysql2_adapter.rb:25:in `mysql2_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:729:in `new_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:773:in `checkout_new_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:752:in `try_to_checkout_new_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:713:in `acquire_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:490:in `checkout'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:364:in `connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:883:in `retrieve_connection'
activerecord (5.0.7.2) lib/active_record/connection_handling.rb:128:in `retrieve_connection'
activerecord (5.0.7.2) lib/active_record/connection_handling.rb:91:in `connection'
activerecord (5.0.7.2) lib/active_record/migration.rb:559:in `connection'
activerecord (5.0.7.2) lib/active_record/migration.rb:546:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:97:in `__run_callbacks__'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:90:in `run_callbacks'
actionpack (5.0.7.2) lib/action_dispatch/middleware/callbacks.rb:36:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.0.7.2) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.0.7.2) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.0.7.2) lib/rails/rack/logger.rb:24:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/request_id.rb:24:in `call'
rack (2.0.6) lib/rack/runtime.rb:22:in `call'
activesupport (5.0.7.2) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/static.rb:136:in `call'
rack (2.0.6) lib/rack/sendfile.rb:111:in `call'
railties (5.0.7.2) lib/rails/engine.rb:522:in `call'
puma (3.12.1) lib/puma/configuration.rb:227:in `call'
puma (3.12.1) lib/puma/server.rb:660:in `handle_request'
puma (3.12.1) lib/puma/server.rb:474:in `process_client'
puma (3.12.1) lib/puma/server.rb:334:in `block in run'
puma (3.12.1) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Started GET "/favicon.ico" for ::1 at 2019-03-19 22:34:13 -0700
  
Mysql2::Error::ConnectionError (Access denied for user 'root'@'localhost' (using password: YES)):
  
mysql2-0.5.2-x86 (mingw32) lib/mysql2/client.rb:90:in `connect'
mysql2-0.5.2-x86 (mingw32) lib/mysql2/client.rb:90:in `initialize'
activerecord (5.0.7.2) lib/active_record/connection_adapters/mysql2_adapter.rb:25:in `new'
activerecord (5.0.7.2) lib/active_record/connection_adapters/mysql2_adapter.rb:25:in `mysql2_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:729:in `new_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:773:in `checkout_new_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:752:in `try_to_checkout_new_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:713:in `acquire_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:490:in `checkout'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:364:in `connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:883:in `retrieve_connection'
activerecord (5.0.7.2) lib/active_record/connection_handling.rb:128:in `retrieve_connection'
activerecord (5.0.7.2) lib/active_record/connection_handling.rb:91:in `connection'
activerecord (5.0.7.2) lib/active_record/migration.rb:559:in `connection'
activerecord (5.0.7.2) lib/active_record/migration.rb:546:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:97:in `__run_callbacks__'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:90:in `run_callbacks'
actionpack (5.0.7.2) lib/action_dispatch/middleware/callbacks.rb:36:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.0.7.2) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.0.7.2) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.0.7.2) lib/rails/rack/logger.rb:24:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/request_id.rb:24:in `call'
rack (2.0.6) lib/rack/runtime.rb:22:in `call'
activesupport (5.0.7.2) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/static.rb:136:in `call'
rack (2.0.6) lib/rack/sendfile.rb:111:in `call'
railties (5.0.7.2) lib/rails/engine.rb:522:in `call'
puma (3.12.1) lib/puma/configuration.rb:227:in `call'
puma (3.12.1) lib/puma/server.rb:660:in `handle_request'
puma (3.12.1) lib/puma/server.rb:474:in `process_client'
puma (3.12.1) lib/puma/server.rb:334:in `block in run'
puma (3.12.1) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Started GET "/" for ::1 at 2019-03-19 22:36:59 -0700
  
Mysql2::Error::ConnectionError (Access denied for user 'root'@'localhost' (using password: YES)):
  
mysql2-0.5.2-x86 (mingw32) lib/mysql2/client.rb:90:in `connect'
mysql2-0.5.2-x86 (mingw32) lib/mysql2/client.rb:90:in `initialize'
activerecord (5.0.7.2) lib/active_record/connection_adapters/mysql2_adapter.rb:25:in `new'
activerecord (5.0.7.2) lib/active_record/connection_adapters/mysql2_adapter.rb:25:in `mysql2_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:729:in `new_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:773:in `checkout_new_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:752:in `try_to_checkout_new_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:713:in `acquire_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:490:in `checkout'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:364:in `connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:883:in `retrieve_connection'
activerecord (5.0.7.2) lib/active_record/connection_handling.rb:128:in `retrieve_connection'
activerecord (5.0.7.2) lib/active_record/connection_handling.rb:91:in `connection'
activerecord (5.0.7.2) lib/active_record/migration.rb:559:in `connection'
activerecord (5.0.7.2) lib/active_record/migration.rb:546:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:97:in `__run_callbacks__'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:90:in `run_callbacks'
actionpack (5.0.7.2) lib/action_dispatch/middleware/callbacks.rb:36:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.0.7.2) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.0.7.2) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.0.7.2) lib/rails/rack/logger.rb:24:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/request_id.rb:24:in `call'
rack (2.0.6) lib/rack/runtime.rb:22:in `call'
activesupport (5.0.7.2) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/static.rb:136:in `call'
rack (2.0.6) lib/rack/sendfile.rb:111:in `call'
railties (5.0.7.2) lib/rails/engine.rb:522:in `call'
puma (3.12.1) lib/puma/configuration.rb:227:in `call'
puma (3.12.1) lib/puma/server.rb:660:in `handle_request'
puma (3.12.1) lib/puma/server.rb:474:in `process_client'
puma (3.12.1) lib/puma/server.rb:334:in `block in run'
puma (3.12.1) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Started GET "/favicon.ico" for ::1 at 2019-03-19 22:37:01 -0700
  
Mysql2::Error::ConnectionError (Access denied for user 'root'@'localhost' (using password: YES)):
  
mysql2-0.5.2-x86 (mingw32) lib/mysql2/client.rb:90:in `connect'
mysql2-0.5.2-x86 (mingw32) lib/mysql2/client.rb:90:in `initialize'
activerecord (5.0.7.2) lib/active_record/connection_adapters/mysql2_adapter.rb:25:in `new'
activerecord (5.0.7.2) lib/active_record/connection_adapters/mysql2_adapter.rb:25:in `mysql2_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:729:in `new_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:773:in `checkout_new_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:752:in `try_to_checkout_new_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:713:in `acquire_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:490:in `checkout'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:364:in `connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:883:in `retrieve_connection'
activerecord (5.0.7.2) lib/active_record/connection_handling.rb:128:in `retrieve_connection'
activerecord (5.0.7.2) lib/active_record/connection_handling.rb:91:in `connection'
activerecord (5.0.7.2) lib/active_record/migration.rb:559:in `connection'
activerecord (5.0.7.2) lib/active_record/migration.rb:546:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:97:in `__run_callbacks__'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:90:in `run_callbacks'
actionpack (5.0.7.2) lib/action_dispatch/middleware/callbacks.rb:36:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.0.7.2) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.0.7.2) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.0.7.2) lib/rails/rack/logger.rb:24:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/request_id.rb:24:in `call'
rack (2.0.6) lib/rack/runtime.rb:22:in `call'
activesupport (5.0.7.2) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/static.rb:136:in `call'
rack (2.0.6) lib/rack/sendfile.rb:111:in `call'
railties (5.0.7.2) lib/rails/engine.rb:522:in `call'
puma (3.12.1) lib/puma/configuration.rb:227:in `call'
puma (3.12.1) lib/puma/server.rb:660:in `handle_request'
puma (3.12.1) lib/puma/server.rb:474:in `process_client'
puma (3.12.1) lib/puma/server.rb:334:in `block in run'
puma (3.12.1) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Started GET "/" for ::1 at 2019-03-19 22:42:01 -0700
  
Mysql2::Error::ConnectionError (Access denied for user 'root'@'localhost' (using password: YES)):
  
mysql2-0.5.2-x86 (mingw32) lib/mysql2/client.rb:90:in `connect'
mysql2-0.5.2-x86 (mingw32) lib/mysql2/client.rb:90:in `initialize'
activerecord (5.0.7.2) lib/active_record/connection_adapters/mysql2_adapter.rb:25:in `new'
activerecord (5.0.7.2) lib/active_record/connection_adapters/mysql2_adapter.rb:25:in `mysql2_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:729:in `new_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:773:in `checkout_new_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:752:in `try_to_checkout_new_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:713:in `acquire_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:490:in `checkout'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:364:in `connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:883:in `retrieve_connection'
activerecord (5.0.7.2) lib/active_record/connection_handling.rb:128:in `retrieve_connection'
activerecord (5.0.7.2) lib/active_record/connection_handling.rb:91:in `connection'
activerecord (5.0.7.2) lib/active_record/migration.rb:559:in `connection'
activerecord (5.0.7.2) lib/active_record/migration.rb:546:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:97:in `__run_callbacks__'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:90:in `run_callbacks'
actionpack (5.0.7.2) lib/action_dispatch/middleware/callbacks.rb:36:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.0.7.2) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.0.7.2) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.0.7.2) lib/rails/rack/logger.rb:24:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/request_id.rb:24:in `call'
rack (2.0.6) lib/rack/runtime.rb:22:in `call'
activesupport (5.0.7.2) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/static.rb:136:in `call'
rack (2.0.6) lib/rack/sendfile.rb:111:in `call'
railties (5.0.7.2) lib/rails/engine.rb:522:in `call'
puma (3.12.1) lib/puma/configuration.rb:227:in `call'
puma (3.12.1) lib/puma/server.rb:660:in `handle_request'
puma (3.12.1) lib/puma/server.rb:474:in `process_client'
puma (3.12.1) lib/puma/server.rb:334:in `block in run'
puma (3.12.1) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Started GET "/favicon.ico" for ::1 at 2019-03-19 22:42:02 -0700
  
Mysql2::Error::ConnectionError (Access denied for user 'root'@'localhost' (using password: YES)):
  
mysql2-0.5.2-x86 (mingw32) lib/mysql2/client.rb:90:in `connect'
mysql2-0.5.2-x86 (mingw32) lib/mysql2/client.rb:90:in `initialize'
activerecord (5.0.7.2) lib/active_record/connection_adapters/mysql2_adapter.rb:25:in `new'
activerecord (5.0.7.2) lib/active_record/connection_adapters/mysql2_adapter.rb:25:in `mysql2_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:729:in `new_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:773:in `checkout_new_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:752:in `try_to_checkout_new_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:713:in `acquire_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:490:in `checkout'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:364:in `connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:883:in `retrieve_connection'
activerecord (5.0.7.2) lib/active_record/connection_handling.rb:128:in `retrieve_connection'
activerecord (5.0.7.2) lib/active_record/connection_handling.rb:91:in `connection'
activerecord (5.0.7.2) lib/active_record/migration.rb:559:in `connection'
activerecord (5.0.7.2) lib/active_record/migration.rb:546:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:97:in `__run_callbacks__'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:90:in `run_callbacks'
actionpack (5.0.7.2) lib/action_dispatch/middleware/callbacks.rb:36:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.0.7.2) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.0.7.2) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.0.7.2) lib/rails/rack/logger.rb:24:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/request_id.rb:24:in `call'
rack (2.0.6) lib/rack/runtime.rb:22:in `call'
activesupport (5.0.7.2) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/static.rb:136:in `call'
rack (2.0.6) lib/rack/sendfile.rb:111:in `call'
railties (5.0.7.2) lib/rails/engine.rb:522:in `call'
puma (3.12.1) lib/puma/configuration.rb:227:in `call'
puma (3.12.1) lib/puma/server.rb:660:in `handle_request'
puma (3.12.1) lib/puma/server.rb:474:in `process_client'
puma (3.12.1) lib/puma/server.rb:334:in `block in run'
puma (3.12.1) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Started GET "/" for ::1 at 2019-03-19 22:43:05 -0700
  
Mysql2::Error::ConnectionError (Access denied for user 'root'@'localhost' (using password: YES)):
  
mysql2-0.5.2-x86 (mingw32) lib/mysql2/client.rb:90:in `connect'
mysql2-0.5.2-x86 (mingw32) lib/mysql2/client.rb:90:in `initialize'
activerecord (5.0.7.2) lib/active_record/connection_adapters/mysql2_adapter.rb:25:in `new'
activerecord (5.0.7.2) lib/active_record/connection_adapters/mysql2_adapter.rb:25:in `mysql2_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:729:in `new_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:773:in `checkout_new_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:752:in `try_to_checkout_new_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:713:in `acquire_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:490:in `checkout'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:364:in `connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:883:in `retrieve_connection'
activerecord (5.0.7.2) lib/active_record/connection_handling.rb:128:in `retrieve_connection'
activerecord (5.0.7.2) lib/active_record/connection_handling.rb:91:in `connection'
activerecord (5.0.7.2) lib/active_record/migration.rb:559:in `connection'
activerecord (5.0.7.2) lib/active_record/migration.rb:546:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:97:in `__run_callbacks__'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:90:in `run_callbacks'
actionpack (5.0.7.2) lib/action_dispatch/middleware/callbacks.rb:36:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.0.7.2) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.0.7.2) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.0.7.2) lib/rails/rack/logger.rb:24:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/request_id.rb:24:in `call'
rack (2.0.6) lib/rack/runtime.rb:22:in `call'
activesupport (5.0.7.2) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/static.rb:136:in `call'
rack (2.0.6) lib/rack/sendfile.rb:111:in `call'
railties (5.0.7.2) lib/rails/engine.rb:522:in `call'
puma (3.12.1) lib/puma/configuration.rb:227:in `call'
puma (3.12.1) lib/puma/server.rb:660:in `handle_request'
puma (3.12.1) lib/puma/server.rb:474:in `process_client'
puma (3.12.1) lib/puma/server.rb:334:in `block in run'
puma (3.12.1) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Started GET "/favicon.ico" for ::1 at 2019-03-19 22:43:06 -0700
  
Mysql2::Error::ConnectionError (Access denied for user 'root'@'localhost' (using password: YES)):
  
mysql2-0.5.2-x86 (mingw32) lib/mysql2/client.rb:90:in `connect'
mysql2-0.5.2-x86 (mingw32) lib/mysql2/client.rb:90:in `initialize'
activerecord (5.0.7.2) lib/active_record/connection_adapters/mysql2_adapter.rb:25:in `new'
activerecord (5.0.7.2) lib/active_record/connection_adapters/mysql2_adapter.rb:25:in `mysql2_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:729:in `new_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:773:in `checkout_new_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:752:in `try_to_checkout_new_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:713:in `acquire_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:490:in `checkout'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:364:in `connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:883:in `retrieve_connection'
activerecord (5.0.7.2) lib/active_record/connection_handling.rb:128:in `retrieve_connection'
activerecord (5.0.7.2) lib/active_record/connection_handling.rb:91:in `connection'
activerecord (5.0.7.2) lib/active_record/migration.rb:559:in `connection'
activerecord (5.0.7.2) lib/active_record/migration.rb:546:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:97:in `__run_callbacks__'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:90:in `run_callbacks'
actionpack (5.0.7.2) lib/action_dispatch/middleware/callbacks.rb:36:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.0.7.2) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.0.7.2) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.0.7.2) lib/rails/rack/logger.rb:24:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/request_id.rb:24:in `call'
rack (2.0.6) lib/rack/runtime.rb:22:in `call'
activesupport (5.0.7.2) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/static.rb:136:in `call'
rack (2.0.6) lib/rack/sendfile.rb:111:in `call'
railties (5.0.7.2) lib/rails/engine.rb:522:in `call'
puma (3.12.1) lib/puma/configuration.rb:227:in `call'
puma (3.12.1) lib/puma/server.rb:660:in `handle_request'
puma (3.12.1) lib/puma/server.rb:474:in `process_client'
puma (3.12.1) lib/puma/server.rb:334:in `block in run'
puma (3.12.1) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Started GET "/" for ::1 at 2019-03-19 22:49:13 -0700
  
Mysql2::Error::ConnectionError (Access denied for user 'root'@'localhost' (using password: YES)):
  
mysql2-0.5.2-x86 (mingw32) lib/mysql2/client.rb:90:in `connect'
mysql2-0.5.2-x86 (mingw32) lib/mysql2/client.rb:90:in `initialize'
activerecord (5.0.7.2) lib/active_record/connection_adapters/mysql2_adapter.rb:25:in `new'
activerecord (5.0.7.2) lib/active_record/connection_adapters/mysql2_adapter.rb:25:in `mysql2_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:729:in `new_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:773:in `checkout_new_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:752:in `try_to_checkout_new_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:713:in `acquire_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:490:in `checkout'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:364:in `connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:883:in `retrieve_connection'
activerecord (5.0.7.2) lib/active_record/connection_handling.rb:128:in `retrieve_connection'
activerecord (5.0.7.2) lib/active_record/connection_handling.rb:91:in `connection'
activerecord (5.0.7.2) lib/active_record/migration.rb:559:in `connection'
activerecord (5.0.7.2) lib/active_record/migration.rb:546:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:97:in `__run_callbacks__'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:90:in `run_callbacks'
actionpack (5.0.7.2) lib/action_dispatch/middleware/callbacks.rb:36:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.0.7.2) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.0.7.2) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.0.7.2) lib/rails/rack/logger.rb:24:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/request_id.rb:24:in `call'
rack (2.0.6) lib/rack/runtime.rb:22:in `call'
activesupport (5.0.7.2) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/static.rb:136:in `call'
rack (2.0.6) lib/rack/sendfile.rb:111:in `call'
railties (5.0.7.2) lib/rails/engine.rb:522:in `call'
puma (3.12.1) lib/puma/configuration.rb:227:in `call'
puma (3.12.1) lib/puma/server.rb:660:in `handle_request'
puma (3.12.1) lib/puma/server.rb:474:in `process_client'
puma (3.12.1) lib/puma/server.rb:334:in `block in run'
puma (3.12.1) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Started GET "/favicon.ico" for ::1 at 2019-03-19 22:49:14 -0700
  
Mysql2::Error::ConnectionError (Access denied for user 'root'@'localhost' (using password: YES)):
  
mysql2-0.5.2-x86 (mingw32) lib/mysql2/client.rb:90:in `connect'
mysql2-0.5.2-x86 (mingw32) lib/mysql2/client.rb:90:in `initialize'
activerecord (5.0.7.2) lib/active_record/connection_adapters/mysql2_adapter.rb:25:in `new'
activerecord (5.0.7.2) lib/active_record/connection_adapters/mysql2_adapter.rb:25:in `mysql2_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:729:in `new_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:773:in `checkout_new_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:752:in `try_to_checkout_new_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:713:in `acquire_connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:490:in `checkout'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:364:in `connection'
activerecord (5.0.7.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:883:in `retrieve_connection'
activerecord (5.0.7.2) lib/active_record/connection_handling.rb:128:in `retrieve_connection'
activerecord (5.0.7.2) lib/active_record/connection_handling.rb:91:in `connection'
activerecord (5.0.7.2) lib/active_record/migration.rb:559:in `connection'
activerecord (5.0.7.2) lib/active_record/migration.rb:546:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:97:in `__run_callbacks__'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:90:in `run_callbacks'
actionpack (5.0.7.2) lib/action_dispatch/middleware/callbacks.rb:36:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.0.7.2) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.0.7.2) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.0.7.2) lib/rails/rack/logger.rb:24:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/request_id.rb:24:in `call'
rack (2.0.6) lib/rack/runtime.rb:22:in `call'
activesupport (5.0.7.2) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/static.rb:136:in `call'
rack (2.0.6) lib/rack/sendfile.rb:111:in `call'
railties (5.0.7.2) lib/rails/engine.rb:522:in `call'
puma (3.12.1) lib/puma/configuration.rb:227:in `call'
puma (3.12.1) lib/puma/server.rb:660:in `handle_request'
puma (3.12.1) lib/puma/server.rb:474:in `process_client'
puma (3.12.1) lib/puma/server.rb:334:in `block in run'
puma (3.12.1) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Started GET "/" for ::1 at 2019-03-19 22:58:28 -0700
Processing by Rails::WelcomeController#index as HTML
  Parameters: {"internal"=>true}
  Rendering C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/railties-5.0.7.2/lib/rails/templates/rails/welcome/index.html.erb
  Rendered C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/railties-5.0.7.2/lib/rails/templates/rails/welcome/index.html.erb (11.5ms)
Completed 200 OK in 83ms (Views: 49.8ms | ActiveRecord: 0.0ms)


Started GET "/favicon.ico" for ::1 at 2019-03-19 22:58:29 -0700
  
ActionController::RoutingError (No route matches [GET] "/favicon.ico"):
  
actionpack (5.0.7.2) lib/action_dispatch/middleware/debug_exceptions.rb:53:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.0.7.2) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.0.7.2) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.0.7.2) lib/rails/rack/logger.rb:24:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/request_id.rb:24:in `call'
rack (2.0.6) lib/rack/runtime.rb:22:in `call'
activesupport (5.0.7.2) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/static.rb:136:in `call'
rack (2.0.6) lib/rack/sendfile.rb:111:in `call'
railties (5.0.7.2) lib/rails/engine.rb:522:in `call'
puma (3.12.1) lib/puma/configuration.rb:227:in `call'
puma (3.12.1) lib/puma/server.rb:660:in `handle_request'
puma (3.12.1) lib/puma/server.rb:474:in `process_client'
puma (3.12.1) lib/puma/server.rb:334:in `block in run'
puma (3.12.1) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Started GET "/" for ::1 at 2019-03-20 09:45:33 -0700
Processing by Rails::WelcomeController#index as HTML
  Parameters: {"internal"=>true}
  Rendering C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/railties-5.0.7.2/lib/rails/templates/rails/welcome/index.html.erb
  Rendered C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/railties-5.0.7.2/lib/rails/templates/rails/welcome/index.html.erb (11.5ms)
Completed 200 OK in 137ms (Views: 63.9ms | ActiveRecord: 0.0ms)


  [1m[35m (28.0ms)[0m  [1m[35mCREATE TABLE `schema_migrations` (`version` varchar(255) PRIMARY KEY) ENGINE=InnoDB[0m
  [1m[35m (6.0ms)[0m  [1m[35mCREATE TABLE `ar_internal_metadata` (`key` varchar(255) PRIMARY KEY, `value` varchar(255), `created_at` datetime NOT NULL, `updated_at` datetime NOT NULL) ENGINE=InnoDB[0m
  [1m[35m (0.0ms)[0m  [1m[34mSELECT DATABASE() as db[0m
  [1m[35m (1.1ms)[0m  [1m[34mSELECT GET_LOCK('3812634849270349410', 0);[0m
  [1m[36mActiveRecord::SchemaMigration Load (3.1ms)[0m  [1m[34mSELECT `schema_migrations`.* FROM `schema_migrations`[0m
Migrating to CreateOrganizationalEvents (20190321004044)
  [1m[35m (6.5ms)[0m  [1m[35mCREATE TABLE `organizational_events` (`id` int AUTO_INCREMENT PRIMARY KEY, `OrganizationName` varchar(255), `HostName` varchar(255), `EventMessage` varchar(255), `text` varchar(255), `EventDateTime` datetime, `created_at` datetime NOT NULL, `updated_at` datetime NOT NULL) ENGINE=InnoDB[0m
  [1m[35m (1.0ms)[0m  [1m[35mBEGIN[0m
  [1m[35mSQL (2.0ms)[0m  [1m[32mINSERT INTO `schema_migrations` (`version`) VALUES ('20190321004044')[0m
  [1m[35m (1.0ms)[0m  [1m[35mCOMMIT[0m
  [1m[36mActiveRecord::InternalMetadata Load (0.5ms)[0m  [1m[34mSELECT  `ar_internal_metadata`.* FROM `ar_internal_metadata` WHERE `ar_internal_metadata`.`key` = 'environment' LIMIT 1[0m
  [1m[35m (0.5ms)[0m  [1m[35mBEGIN[0m
  [1m[35mSQL (0.5ms)[0m  [1m[32mINSERT INTO `ar_internal_metadata` (`key`, `value`, `created_at`, `updated_at`) VALUES ('environment', 'development', '2019-03-21 00:46:23', '2019-03-21 00:46:23')[0m
  [1m[35m (1.0ms)[0m  [1m[35mCOMMIT[0m
  [1m[35m (1.0ms)[0m  [1m[34mSELECT RELEASE_LOCK('3812634849270349410')[0m
  [1m[36mActiveRecord::SchemaMigration Load (0.5ms)[0m  [1m[34mSELECT `schema_migrations`.* FROM `schema_migrations`[0m
  [1m[35m (0.0ms)[0m  [1m[35mSHOW CREATE TABLE `organizational_events`[0m
  [1m[35m (1.5ms)[0m  [1m[35mSHOW TABLE STATUS LIKE 'organizational_events'[0m
  [1m[36mActiveRecord::SchemaMigration Load (2.0ms)[0m  [1m[34mSELECT `schema_migrations`.* FROM `schema_migrations`[0m
  [1m[35m (0.5ms)[0m  [1m[35mBEGIN[0m
  [1m[35mSQL (2.0ms)[0m  [1m[32mINSERT INTO `organizational_events` (`OrganizationName`, `HostName`, `EventMessage`, `EventDateTime`, `created_at`, `updated_at`) VALUES ('Nutanix', 'Alekha Ojha', 'Hello this is Alekh', '2019-03-21 01:06:53', '2019-03-21 01:06:53', '2019-03-21 01:06:53')[0m
  [1m[35m (1.0ms)[0m  [1m[35mCOMMIT[0m
  [1m[35m (0.0ms)[0m  [1m[35mBEGIN[0m
  [1m[35mSQL (0.5ms)[0m  [1m[32mINSERT INTO `organizational_events` (`OrganizationName`, `HostName`, `EventMessage`, `EventDateTime`, `created_at`, `updated_at`) VALUES ('Nutanix', 'Alekha Ojha', 'Hello this is Alekh', '2019-03-21 01:06:53', '2019-03-21 01:06:53', '2019-03-21 01:06:53')[0m
  [1m[35m (1.0ms)[0m  [1m[35mCOMMIT[0m
Started GET "/api/v1/events" for ::1 at 2019-03-20 19:58:34 -0700
  [1m[36mActiveRecord::SchemaMigration Load (2.3ms)[0m  [1m[34mSELECT `schema_migrations`.* FROM `schema_migrations`[0m
  
SyntaxError (C:/Sites/OrganizationalEvents/app/controllers/api/v1/events_controller.rb:5: dynamic constant assignment
        OrganizationEvents = OrganizationalEvent.order('c...
                            ^):
  
app/controllers/api/v1/events_controller.rb:5: dynamic constant assignment
Started GET "/api/v1/events" for ::1 at 2019-03-20 20:01:52 -0700
  
SyntaxError (C:/Sites/OrganizationalEvents/app/controllers/api/v1/events_controller.rb:5: dynamic constant assignment
        OrganizationEvents = OrganizationalEvent.order('c...
                            ^):
  
app/controllers/api/v1/events_controller.rb:5: dynamic constant assignment
Started GET "/api/v1/events" for ::1 at 2019-03-20 20:05:30 -0700
  
SyntaxError (C:/Sites/OrganizationalEvents/app/controllers/api/v1/events_controller.rb:5: dynamic constant assignment
        OrganizationEvents = OrganizationalEvent.order("c...
                            ^):
  
app/controllers/api/v1/events_controller.rb:5: dynamic constant assignment
Started GET "/api/v1/events" for ::1 at 2019-03-20 20:06:24 -0700
  
SyntaxError (C:/Sites/OrganizationalEvents/app/controllers/api/v1/events_controller.rb:5: dynamic constant assignment
        OrganizationEvents = OrganizationalEvent.order('c...
                            ^):
  
app/controllers/api/v1/events_controller.rb:5: dynamic constant assignment
Started GET "/api/v1/events" for ::1 at 2019-03-20 20:08:43 -0700
  
SyntaxError (C:/Sites/OrganizationalEvents/app/controllers/api/v1/events_controller.rb:5: dynamic constant assignment
        OrganizationEvents = OrganizationalEvent.order('c...
                            ^):
  
app/controllers/api/v1/events_controller.rb:5: dynamic constant assignment
Started GET "/api/v1/events" for ::1 at 2019-03-20 20:09:45 -0700
  
SyntaxError (C:/Sites/OrganizationalEvents/app/controllers/api/v1/events_controller.rb:5: dynamic constant assignment
        OrganizationEvents = OrganizationalEvent.order('c...
                            ^):
  
app/controllers/api/v1/events_controller.rb:5: dynamic constant assignment
Started GET "/api/v1/events" for ::1 at 2019-03-20 20:12:44 -0700
  
SyntaxError (C:/Sites/OrganizationalEvents/app/controllers/api/v1/events_controller.rb:6: dynamic constant assignment
        OrganizationEvents = OrganizationalEvent.order(strquery);
                            ^):
  
app/controllers/api/v1/events_controller.rb:6: dynamic constant assignment
Started GET "/api/v1/events" for ::1 at 2019-03-20 20:14:30 -0700
  
SyntaxError (C:/Sites/OrganizationalEvents/app/controllers/api/v1/events_controller.rb:6: dynamic constant assignment
        OrganizationEvents = OrganizationalEvent.order(strquery)
                            ^):
  
app/controllers/api/v1/events_controller.rb:6: dynamic constant assignment
Started GET "/api/v1/events" for ::1 at 2019-03-20 20:21:31 -0700
  
SyntaxError (C:/Sites/OrganizationalEvents/app/controllers/api/v1/events_controller.rb:6: dynamic constant assignment
        OrganizationEvents = OrganizationalEvent.order()
                            ^):
  
app/controllers/api/v1/events_controller.rb:6: dynamic constant assignment
Started GET "/api/v1/events" for ::1 at 2019-03-20 20:22:04 -0700
  
SyntaxError (C:/Sites/OrganizationalEvents/app/controllers/api/v1/events_controller.rb:6: dynamic constant assignment
        OrganizationEvents=OrganizationalEvent.order()
                           ^):
  
app/controllers/api/v1/events_controller.rb:6: dynamic constant assignment
Started GET "/api/v1/events" for ::1 at 2019-03-20 20:22:15 -0700
  
SyntaxError (C:/Sites/OrganizationalEvents/app/controllers/api/v1/events_controller.rb:6: dynamic constant assignment
        OrganizationEvents =OrganizationalEvent.order()
                            ^):
  
app/controllers/api/v1/events_controller.rb:6: dynamic constant assignment
Started GET "/api/v1/events" for ::1 at 2019-03-20 20:22:50 -0700
  
SyntaxError (C:/Sites/OrganizationalEvents/app/controllers/api/v1/events_controller.rb:6: dynamic constant assignment
        OrganizationEvents = OrganizationalEvent.order(strquery);
                            ^):
  
app/controllers/api/v1/events_controller.rb:6: dynamic constant assignment
Started GET "/api/v1/events" for ::1 at 2019-03-20 20:23:31 -0700
  
SyntaxError (C:/Sites/OrganizationalEvents/app/controllers/api/v1/events_controller.rb:6: dynamic constant assignment
        OrganizationEvents = OrganizationalEvent.order(strquery);
                            ^):
  
app/controllers/api/v1/events_controller.rb:6: dynamic constant assignment
Started GET "/api/v1/events" for ::1 at 2019-03-20 20:24:51 -0700
  
SyntaxError (C:/Sites/OrganizationalEvents/app/controllers/api/v1/events_controller.rb:6: dynamic constant assignment
        OrganizationEvents = OrganizationalEvent.order(strquery);
                            ^):
  
app/controllers/api/v1/events_controller.rb:6: dynamic constant assignment
Started GET "/api/v1/events" for ::1 at 2019-03-20 20:26:25 -0700
  
SyntaxError (C:/Sites/OrganizationalEvents/app/controllers/api/v1/events_controller.rb:6: dynamic constant assignment
        OrganizationEvents = OrganizationalEvent;
                            ^):
  
app/controllers/api/v1/events_controller.rb:6: dynamic constant assignment
Started GET "/api/v1/events" for ::1 at 2019-03-20 20:32:37 -0700
Processing by Api::V1::EventsController#index as */*
Completed 500 Internal Server Error in 7ms (ActiveRecord: 0.0ms)


  
SyntaxError (C:/Sites/OrganizationalEvents/app/models/organizational_event.rb:2: syntax error, unexpected ':', expecting keyword_end
  validate :OrganizationName, presence : true
                                        ^
C:/Sites/OrganizationalEvents/app/models/organizational_event.rb:3: syntax error, unexpected ':', expecting keyword_end
  validate :HostName, presence : true
                                ^
C:/Sites/OrganizationalEvents/app/models/organizational_event.rb:4: syntax error, unexpected ':', expecting keyword_end
  validate :EventMessage, presence : true
                                    ^
C:/Sites/OrganizationalEvents/app/models/organizational_event.rb:5: syntax error, unexpected ':', expecting keyword_end
  validate :EventDateTime, presence : true
                                     ^):
  
app/models/organizational_event.rb:2: syntax error, unexpected ':', expecting keyword_end
app/models/organizational_event.rb:3: syntax error, unexpected ':', expecting keyword_end
app/models/organizational_event.rb:4: syntax error, unexpected ':', expecting keyword_end
app/models/organizational_event.rb:5: syntax error, unexpected ':', expecting keyword_end
app/controllers/api/v1/events_controller.rb:5:in `index'
Started GET "/api/v1/events" for ::1 at 2019-03-20 20:33:44 -0700
Processing by Api::V1::EventsController#index as */*
Completed 500 Internal Server Error in 5ms (ActiveRecord: 0.0ms)


  
SyntaxError (C:/Sites/OrganizationalEvents/app/models/organizational_event.rb:2: syntax error, unexpected ':', expecting keyword_end
  validate :OrganizationName, presence : true
                                        ^
C:/Sites/OrganizationalEvents/app/models/organizational_event.rb:3: syntax error, unexpected ':', expecting keyword_end
  validate :HostName, presence : true
                                ^
C:/Sites/OrganizationalEvents/app/models/organizational_event.rb:4: syntax error, unexpected ':', expecting keyword_end
  validate :EventMessage, presence : true
                                    ^
C:/Sites/OrganizationalEvents/app/models/organizational_event.rb:5: syntax error, unexpected ':', expecting keyword_end
  validate :EventDateTime, presence : true
                                     ^):
  
app/models/organizational_event.rb:2: syntax error, unexpected ':', expecting keyword_end
app/models/organizational_event.rb:3: syntax error, unexpected ':', expecting keyword_end
app/models/organizational_event.rb:4: syntax error, unexpected ':', expecting keyword_end
app/models/organizational_event.rb:5: syntax error, unexpected ':', expecting keyword_end
app/controllers/api/v1/events_controller.rb:5:in `index'
Started GET "/api/v1/events" for ::1 at 2019-03-20 20:34:37 -0700
  
SyntaxError (C:/Sites/OrganizationalEvents/app/controllers/api/v1/events_controller.rb:6: syntax error, unexpected ':'
...:@OrganizationEvents},status: : ok
...                               ^):
  
app/controllers/api/v1/events_controller.rb:6: syntax error, unexpected ':'
Started GET "/api/v1/events" for ::1 at 2019-03-20 20:35:08 -0700
  
SyntaxError (C:/Sites/OrganizationalEvents/app/controllers/api/v1/events_controller.rb:6: syntax error, unexpected ':'
...a:OrganizationEvents},status: : ok
...                               ^):
  
app/controllers/api/v1/events_controller.rb:6: syntax error, unexpected ':'
Started GET "/api/v1/events" for ::1 at 2019-03-20 20:35:23 -0700
Processing by Api::V1::EventsController#index as */*
Completed 500 Internal Server Error in 4ms (ActiveRecord: 0.0ms)


  
SyntaxError (C:/Sites/OrganizationalEvents/app/models/organizational_event.rb:2: syntax error, unexpected ':', expecting keyword_end
  validate :OrganizationName, presence : true
                                        ^
C:/Sites/OrganizationalEvents/app/models/organizational_event.rb:3: syntax error, unexpected ':', expecting keyword_end
  validate :HostName, presence : true
                                ^
C:/Sites/OrganizationalEvents/app/models/organizational_event.rb:4: syntax error, unexpected ':', expecting keyword_end
  validate :EventMessage, presence : true
                                    ^
C:/Sites/OrganizationalEvents/app/models/organizational_event.rb:5: syntax error, unexpected ':', expecting keyword_end
  validate :EventDateTime, presence : true
                                     ^):
  
app/models/organizational_event.rb:2: syntax error, unexpected ':', expecting keyword_end
app/models/organizational_event.rb:3: syntax error, unexpected ':', expecting keyword_end
app/models/organizational_event.rb:4: syntax error, unexpected ':', expecting keyword_end
app/models/organizational_event.rb:5: syntax error, unexpected ':', expecting keyword_end
app/controllers/api/v1/events_controller.rb:5:in `index'
Started GET "/api/v1/events" for ::1 at 2019-03-20 20:35:49 -0700
Processing by Api::V1::EventsController#index as */*
Completed 500 Internal Server Error in 5ms (ActiveRecord: 0.0ms)


  
SyntaxError (C:/Sites/OrganizationalEvents/app/models/organizational_event.rb:2: syntax error, unexpected ':', expecting keyword_end
  validate :OrganizationName, presence : true
                                        ^
C:/Sites/OrganizationalEvents/app/models/organizational_event.rb:3: syntax error, unexpected ':', expecting keyword_end
  validate :HostName, presence : true
                                ^
C:/Sites/OrganizationalEvents/app/models/organizational_event.rb:4: syntax error, unexpected ':', expecting keyword_end
  validate :EventMessage, presence : true
                                    ^
C:/Sites/OrganizationalEvents/app/models/organizational_event.rb:5: syntax error, unexpected ':', expecting keyword_end
  validate :EventDateTime, presence : true
                                     ^):
  
app/models/organizational_event.rb:2: syntax error, unexpected ':', expecting keyword_end
app/models/organizational_event.rb:3: syntax error, unexpected ':', expecting keyword_end
app/models/organizational_event.rb:4: syntax error, unexpected ':', expecting keyword_end
app/models/organizational_event.rb:5: syntax error, unexpected ':', expecting keyword_end
app/controllers/api/v1/events_controller.rb:5:in `index'
Started GET "/api/v1/events" for ::1 at 2019-03-20 20:37:33 -0700
Processing by Api::V1::EventsController#index as */*
Completed 500 Internal Server Error in 5ms (ActiveRecord: 0.0ms)


  
SyntaxError (C:/Sites/OrganizationalEvents/app/models/organizational_event.rb:2: syntax error, unexpected ':', expecting keyword_end
  validate :OrganizationName, presence : true
                                        ^
C:/Sites/OrganizationalEvents/app/models/organizational_event.rb:3: syntax error, unexpected ':', expecting keyword_end
  validate :HostName, presence : true
                                ^
C:/Sites/OrganizationalEvents/app/models/organizational_event.rb:4: syntax error, unexpected ':', expecting keyword_end
  validate :EventMessage, presence : true
                                    ^
C:/Sites/OrganizationalEvents/app/models/organizational_event.rb:5: syntax error, unexpected ':', expecting keyword_end
  validate :EventDateTime, presence : true
                                     ^):
  
app/models/organizational_event.rb:2: syntax error, unexpected ':', expecting keyword_end
app/models/organizational_event.rb:3: syntax error, unexpected ':', expecting keyword_end
app/models/organizational_event.rb:4: syntax error, unexpected ':', expecting keyword_end
app/models/organizational_event.rb:5: syntax error, unexpected ':', expecting keyword_end
app/controllers/api/v1/events_controller.rb:5:in `index'
Started GET "/api/v1/events" for ::1 at 2019-03-20 20:39:14 -0700
Processing by Api::V1::EventsController#index as */*
Completed 500 Internal Server Error in 18ms (ActiveRecord: 0.0ms)


  
ArgumentError (Unknown key: :presence. Valid keys are: :on, :if, :unless, :prepend. Perhaps you meant to call `validates` instead of `validate`?):
  
app/models/organizational_event.rb:2:in `<class:OrganizationalEvent>'
app/models/organizational_event.rb:1:in `<top (required)>'
app/controllers/api/v1/events_controller.rb:5:in `index'
Started GET "/api/v1/events" for ::1 at 2019-03-20 20:41:53 -0700
Processing by Api::V1::EventsController#index as */*
Completed 500 Internal Server Error in 46ms (ActiveRecord: 0.0ms)


  
NameError (uninitialized constant Api::V1::EventsController::OrganizationEvents):
  
app/controllers/api/v1/events_controller.rb:6:in `index'
Started GET "/api/v1/events" for ::1 at 2019-03-20 20:43:11 -0700
Processing by Api::V1::EventsController#index as */*
Completed 500 Internal Server Error in 4ms (ActiveRecord: 0.0ms)


  
NameError (uninitialized constant Api::V1::EventsController::OrganizationEvents):
  
app/controllers/api/v1/events_controller.rb:6:in `index'
Started GET "/api/v1/events" for ::1 at 2019-03-20 20:44:56 -0700
  
SyntaxError (C:/Sites/OrganizationalEvents/app/controllers/api/v1/events_controller.rb:6: syntax error, unexpected ':'
...a:OrganizationEvents},status: : ok
...                               ^):
  
app/controllers/api/v1/events_controller.rb:6: syntax error, unexpected ':'
Started GET "/api/v1/events" for ::1 at 2019-03-20 20:45:10 -0700
Processing by Api::V1::EventsController#index as */*
Completed 500 Internal Server Error in 11ms (ActiveRecord: 0.0ms)


  
NameError (uninitialized constant Api::V1::EventsController::OrganizationEvents):
  
app/controllers/api/v1/events_controller.rb:6:in `index'
Started GET "/api/v1/events" for ::1 at 2019-03-20 20:45:30 -0700
Processing by Api::V1::EventsController#index as */*
  [1m[36mOrganizationalEvent Load (7.5ms)[0m  [1m[34mSELECT `organizational_events`.* FROM `organizational_events` ORDER BY created_at DESC[0m
Completed 200 OK in 75ms (Views: 46.6ms | ActiveRecord: 14.0ms)


Started GET "/api/v1/events" for ::1 at 2019-03-20 22:31:22 -0700
Processing by Api::V1::EventsController#index as */*
  [1m[36mOrganizationalEvent Load (18.5ms)[0m  [1m[34mSELECT `organizational_events`.* FROM `organizational_events` ORDER BY created_at DESC[0m
Completed 200 OK in 70ms (Views: 34.4ms | ActiveRecord: 18.5ms)


Started GET "/api/v1/events/1" for ::1 at 2019-03-20 22:36:45 -0700
Processing by Api::V1::EventsController#show as */*
  Parameters: {"id"=>"1"}
  [1m[36mOrganizationalEvent Load (1.5ms)[0m  [1m[34mSELECT  `organizational_events`.* FROM `organizational_events` WHERE `organizational_events`.`id` = 1 LIMIT 1[0m
Completed 200 OK in 50ms (Views: 1.1ms | ActiveRecord: 1.5ms)


Started GET "/api/v1/events/Nutanix" for ::1 at 2019-03-20 22:41:27 -0700
Processing by Api::V1::EventsController#show as */*
  Parameters: {"id"=>"Nutanix"}
  [1m[36mOrganizationalEvent Load (2.0ms)[0m  [1m[34mSELECT  `organizational_events`.* FROM `organizational_events` WHERE `organizational_events`.`id` = NULL LIMIT 1[0m
Completed 404 Not Found in 22ms (ActiveRecord: 2.0ms)


  
ActiveRecord::RecordNotFound (Couldn't find OrganizationalEvent with 'id'=):
  
app/controllers/api/v1/events_controller.rb:9:in `show'
Started GET "/api/v1/events/1" for ::1 at 2019-03-20 22:41:42 -0700
Processing by Api::V1::EventsController#show as */*
  Parameters: {"id"=>"1"}
  [1m[36mOrganizationalEvent Load (4.0ms)[0m  [1m[34mSELECT  `organizational_events`.* FROM `organizational_events` WHERE `organizational_events`.`id` = NULL LIMIT 1[0m
Completed 404 Not Found in 7ms (ActiveRecord: 4.0ms)


  
ActiveRecord::RecordNotFound (Couldn't find OrganizationalEvent with 'id'=):
  
app/controllers/api/v1/events_controller.rb:9:in `show'
Started GET "/api/v1/events/Nutanix" for ::1 at 2019-03-20 22:42:41 -0700
Processing by Api::V1::EventsController#show as */*
  Parameters: {"id"=>"Nutanix"}
  [1m[36mOrganizationalEvent Load (2.0ms)[0m  [1m[34mSELECT  `organizational_events`.* FROM `organizational_events` WHERE `organizational_events`.`id` = NULL LIMIT 1[0m
Completed 404 Not Found in 5ms (ActiveRecord: 2.0ms)


  
ActiveRecord::RecordNotFound (Couldn't find OrganizationalEvent with 'id'=):
  
app/controllers/api/v1/events_controller.rb:9:in `show'
Started GET "/api/v1/events/Nutanix" for ::1 at 2019-03-20 22:43:10 -0700
Processing by Api::V1::EventsController#show as */*
  Parameters: {"id"=>"Nutanix"}
  [1m[36mOrganizationalEvent Load (1.5ms)[0m  [1m[34mSELECT  `organizational_events`.* FROM `organizational_events` WHERE `organizational_events`.`id` = NULL LIMIT 1[0m
Completed 404 Not Found in 4ms (ActiveRecord: 1.5ms)


  
ActiveRecord::RecordNotFound (Couldn't find OrganizationalEvent with 'id'=):
  
app/controllers/api/v1/events_controller.rb:9:in `show'
Started GET "/api/v1/events/Nutanix" for ::1 at 2019-03-20 22:43:53 -0700
  
SyntaxError (C:/Sites/OrganizationalEvents/app/controllers/api/v1/events_controller.rb:9: syntax error, unexpected ':', expecting ']'
...ganizationalEvent.find(params[: OrganizationName]);
...                               ^):
  
app/controllers/api/v1/events_controller.rb:9: syntax error, unexpected ':', expecting ']'
Started GET "/api/v1/events/Nutanix" for ::1 at 2019-03-20 22:44:34 -0700
Processing by Api::V1::EventsController#show as */*
  Parameters: {"id"=>"Nutanix"}
  [1m[36mOrganizationalEvent Load (1.0ms)[0m  [1m[34mSELECT  `organizational_events`.* FROM `organizational_events` WHERE `organizational_events`.`id` = 0 LIMIT 1[0m
Completed 404 Not Found in 27ms (ActiveRecord: 9.0ms)


  
ActiveRecord::RecordNotFound (Couldn't find OrganizationalEvent with 'id'=Nutanix):
  
app/controllers/api/v1/events_controller.rb:9:in `show'
Started GET "/api/v1/events/1" for ::1 at 2019-03-20 22:44:43 -0700
Processing by Api::V1::EventsController#show as */*
  Parameters: {"id"=>"1"}
  [1m[36mOrganizationalEvent Load (1.5ms)[0m  [1m[34mSELECT  `organizational_events`.* FROM `organizational_events` WHERE `organizational_events`.`id` = 1 LIMIT 1[0m
Completed 200 OK in 18ms (Views: 1.4ms | ActiveRecord: 2.5ms)


Started GET "/api/v1/events/2" for ::1 at 2019-03-20 22:44:50 -0700
Processing by Api::V1::EventsController#show as */*
  Parameters: {"id"=>"2"}
  [1m[36mOrganizationalEvent Load (2.5ms)[0m  [1m[34mSELECT  `organizational_events`.* FROM `organizational_events` WHERE `organizational_events`.`id` = 2 LIMIT 1[0m
Completed 200 OK in 6ms (Views: 1.2ms | ActiveRecord: 2.5ms)


Started POST "/api/v1/events" for ::1 at 2019-03-20 23:03:45 -0700
Processing by Api::V1::EventsController#create as */*
  Parameters: {"OrganizationName"=>"Nutanix", "HostName"=>"Alekha Ojha", "EventMessage"=>"Hello this is Alekh", "EventDateTime"=>"2019-03-21T01:06:53.000Z", "event"=>{"OrganizationName"=>"Nutanix", "HostName"=>"Alekha Ojha", "EventMessage"=>"Hello this is Alekh", "EventDateTime"=>"2019-03-21T01:06:53.000Z"}}
Unpermitted parameter: event
  [1m[35m (1.0ms)[0m  [1m[35mBEGIN[0m
  [1m[35mSQL (7.5ms)[0m  [1m[32mINSERT INTO `organizational_events` (`OrganizationName`, `HostName`, `EventMessage`, `EventDateTime`, `created_at`, `updated_at`) VALUES ('Nutanix', 'Alekha Ojha', 'Hello this is Alekh', '2019-03-21 01:06:53', '2019-03-21 06:03:45', '2019-03-21 06:03:45')[0m
  [1m[35m (3.5ms)[0m  [1m[35mCOMMIT[0m
Completed 200 OK in 76ms (Views: 3.7ms | ActiveRecord: 12.0ms)


Started POST "/api/v1/events" for ::1 at 2019-03-20 23:04:19 -0700
Processing by Api::V1::EventsController#create as */*
  Parameters: {"OrganizationName"=>"ILLUMINA", "HostName"=>"Alekha Ojha", "EventMessage"=>"Hello this is Alekh", "EventDateTime"=>"2019-03-27T01:06:53.000Z", "event"=>{"OrganizationName"=>"ILLUMINA", "HostName"=>"Alekha Ojha", "EventMessage"=>"Hello this is Alekh", "EventDateTime"=>"2019-03-27T01:06:53.000Z"}}
Unpermitted parameter: event
  [1m[35m (0.5ms)[0m  [1m[35mBEGIN[0m
  [1m[35mSQL (0.5ms)[0m  [1m[32mINSERT INTO `organizational_events` (`OrganizationName`, `HostName`, `EventMessage`, `EventDateTime`, `created_at`, `updated_at`) VALUES ('ILLUMINA', 'Alekha Ojha', 'Hello this is Alekh', '2019-03-27 01:06:53', '2019-03-21 06:04:19', '2019-03-21 06:04:19')[0m
  [1m[35m (2.5ms)[0m  [1m[35mCOMMIT[0m
Completed 200 OK in 16ms (Views: 0.9ms | ActiveRecord: 3.5ms)


Started GET "/api/v1/events" for ::1 at 2019-03-20 23:04:32 -0700
Processing by Api::V1::EventsController#index as */*
  [1m[36mOrganizationalEvent Load (3.0ms)[0m  [1m[34mSELECT `organizational_events`.* FROM `organizational_events` ORDER BY created_at DESC[0m
Completed 200 OK in 9ms (Views: 5.9ms | ActiveRecord: 3.0ms)


Started DELETE "/api/v1/events/3" for ::1 at 2019-03-20 23:11:59 -0700
Processing by Api::V1::EventsController#destroy as */*
  Parameters: {"id"=>"3"}
  [1m[36mOrganizationalEvent Load (0.5ms)[0m  [1m[34mSELECT  `organizational_events`.* FROM `organizational_events` WHERE `organizational_events`.`id` = 3 LIMIT 1[0m
  [1m[35m (0.5ms)[0m  [1m[35mBEGIN[0m
  [1m[35mSQL (32.4ms)[0m  [1m[31mDELETE FROM `organizational_events` WHERE `organizational_events`.`id` = 3[0m
  [1m[35m (1.0ms)[0m  [1m[35mCOMMIT[0m
Completed 200 OK in 78ms (Views: 1.5ms | ActiveRecord: 34.4ms)


Started GET "/api/v1/events" for ::1 at 2019-03-20 23:12:18 -0700
Processing by Api::V1::EventsController#index as */*
  [1m[36mOrganizationalEvent Load (3.0ms)[0m  [1m[34mSELECT `organizational_events`.* FROM `organizational_events` ORDER BY created_at DESC[0m
Completed 200 OK in 9ms (Views: 5.2ms | ActiveRecord: 3.0ms)


Started PUT "/api/v1/events/3" for ::1 at 2019-03-20 23:24:26 -0700
Processing by Api::V1::EventsController#update as */*
  Parameters: {"OrganizationName"=>"Nutanix Inc", "HostName"=>"Alekha Ojha", "EventMessage"=>"Hello this is an update from Alekh", "EventDateTime"=>"2019-03-31T01:06:53.000Z", "id"=>"3", "event"=>{"OrganizationName"=>"Nutanix Inc", "HostName"=>"Alekha Ojha", "EventMessage"=>"Hello this is an update from Alekh", "EventDateTime"=>"2019-03-31T01:06:53.000Z"}}
  [1m[36mOrganizationalEvent Load (0.5ms)[0m  [1m[34mSELECT  `organizational_events`.* FROM `organizational_events` WHERE `organizational_events`.`id` = 3 LIMIT 1[0m
Completed 404 Not Found in 33ms (ActiveRecord: 6.5ms)


  
ActiveRecord::RecordNotFound (Couldn't find OrganizationalEvent with 'id'=3):
  
app/controllers/api/v1/events_controller.rb:26:in `update'
Started PUT "/api/v1/events/2" for ::1 at 2019-03-20 23:24:37 -0700
Processing by Api::V1::EventsController#update as */*
  Parameters: {"OrganizationName"=>"Nutanix Inc", "HostName"=>"Alekha Ojha", "EventMessage"=>"Hello this is an update from Alekh", "EventDateTime"=>"2019-03-31T01:06:53.000Z", "id"=>"2", "event"=>{"OrganizationName"=>"Nutanix Inc", "HostName"=>"Alekha Ojha", "EventMessage"=>"Hello this is an update from Alekh", "EventDateTime"=>"2019-03-31T01:06:53.000Z"}}
  [1m[36mOrganizationalEvent Load (1.0ms)[0m  [1m[34mSELECT  `organizational_events`.* FROM `organizational_events` WHERE `organizational_events`.`id` = 2 LIMIT 1[0m
Completed 500 Internal Server Error in 32ms (ActiveRecord: 2.5ms)


  
NameError (uninitialized constant Api::V1::EventsController::OrganizationEvent):
  
app/controllers/api/v1/events_controller.rb:27:in `update'
Started PUT "/api/v1/events/2" for ::1 at 2019-03-20 23:25:12 -0700
Processing by Api::V1::EventsController#update as */*
  Parameters: {"OrganizationName"=>"Nutanix Inc", "HostName"=>"Alekha Ojha", "EventMessage"=>"Hello this is an update from Alekh", "EventDateTime"=>"2019-03-22T01:06:53.000Z", "id"=>"2", "event"=>{"OrganizationName"=>"Nutanix Inc", "HostName"=>"Alekha Ojha", "EventMessage"=>"Hello this is an update from Alekh", "EventDateTime"=>"2019-03-22T01:06:53.000Z"}}
  [1m[36mOrganizationalEvent Load (1.5ms)[0m  [1m[34mSELECT  `organizational_events`.* FROM `organizational_events` WHERE `organizational_events`.`id` = 2 LIMIT 1[0m
Completed 500 Internal Server Error in 11ms (ActiveRecord: 1.5ms)


  
NameError (uninitialized constant Api::V1::EventsController::OrganizationEvent):
  
app/controllers/api/v1/events_controller.rb:27:in `update'
Started PUT "/api/v1/events/2" for ::1 at 2019-03-20 23:26:02 -0700
Processing by Api::V1::EventsController#update as */*
  Parameters: {"OrganizationName"=>"Nutanix Inc", "HostName"=>"Alekha Ojha", "EventMessage"=>"Hello this is an update from Alekh", "EventDateTime"=>"2019-03-22T01:06:53.000Z", "id"=>"2", "event"=>{"OrganizationName"=>"Nutanix Inc", "HostName"=>"Alekha Ojha", "EventMessage"=>"Hello this is an update from Alekh", "EventDateTime"=>"2019-03-22T01:06:53.000Z"}}
  [1m[36mOrganizationalEvent Load (1.5ms)[0m  [1m[34mSELECT  `organizational_events`.* FROM `organizational_events` WHERE `organizational_events`.`id` = 2 LIMIT 1[0m
Completed 500 Internal Server Error in 12ms (ActiveRecord: 1.5ms)


  
NameError (uninitialized constant Api::V1::EventsController::OrganizationEvent):
  
app/controllers/api/v1/events_controller.rb:27:in `update'
Started PUT "/api/v1/events/2" for ::1 at 2019-03-20 23:28:31 -0700
Processing by Api::V1::EventsController#update as */*
  Parameters: {"OrganizationName"=>"Nutanix Inc", "HostName"=>"Alekha Ojha", "EventMessage"=>"Hello this is an update from Alekh", "EventDateTime"=>"2019-03-22T01:06:53.000Z", "id"=>"2", "event"=>{"OrganizationName"=>"Nutanix Inc", "HostName"=>"Alekha Ojha", "EventMessage"=>"Hello this is an update from Alekh", "EventDateTime"=>"2019-03-22T01:06:53.000Z"}}
  [1m[36mOrganizationalEvent Load (1.0ms)[0m  [1m[34mSELECT  `organizational_events`.* FROM `organizational_events` WHERE `organizational_events`.`id` = 2 LIMIT 1[0m
Unpermitted parameters: id, event
  [1m[35m (0.5ms)[0m  [1m[35mBEGIN[0m
  [1m[35mSQL (2.0ms)[0m  [1m[33mUPDATE `organizational_events` SET `OrganizationName` = 'Nutanix Inc', `EventMessage` = 'Hello this is an update from Alekh', `EventDateTime` = '2019-03-22 01:06:53', `updated_at` = '2019-03-21 06:28:31' WHERE `organizational_events`.`id` = 2[0m
  [1m[35m (3.0ms)[0m  [1m[35mCOMMIT[0m
Completed 200 OK in 60ms (Views: 1.0ms | ActiveRecord: 11.0ms)


  [1m[35m (0.5ms)[0m  [1m[34mSELECT DATABASE() as db[0m
  [1m[35m (1.2ms)[0m  [1m[34mSELECT GET_LOCK('3812634849270349410', 0);[0m
  [1m[36mActiveRecord::SchemaMigration Load (4.5ms)[0m  [1m[34mSELECT `schema_migrations`.* FROM `schema_migrations`[0m
Migrating to CreateOrganizations (20190322032152)
  [1m[35m (33.4ms)[0m  [1m[35mCREATE TABLE `organizations` (`id` int AUTO_INCREMENT PRIMARY KEY, `orgname` varchar(255), `country` varchar(255), `state` varchar(255), `city` varchar(255), `street` varchar(255), `created_at` datetime NOT NULL, `updated_at` datetime NOT NULL) ENGINE=InnoDB[0m
  [1m[35m (0.5ms)[0m  [1m[35mBEGIN[0m
  [1m[35mSQL (1.0ms)[0m  [1m[32mINSERT INTO `schema_migrations` (`version`) VALUES ('20190322032152')[0m
  [1m[35m (1.0ms)[0m  [1m[35mCOMMIT[0m
  [1m[36mActiveRecord::InternalMetadata Load (2.6ms)[0m  [1m[34mSELECT  `ar_internal_metadata`.* FROM `ar_internal_metadata` WHERE `ar_internal_metadata`.`key` = 'environment' LIMIT 1[0m
  [1m[35m (0.5ms)[0m  [1m[35mBEGIN[0m
  [1m[35m (0.0ms)[0m  [1m[35mCOMMIT[0m
  [1m[35m (0.0ms)[0m  [1m[34mSELECT RELEASE_LOCK('3812634849270349410')[0m
  [1m[36mActiveRecord::SchemaMigration Load (0.0ms)[0m  [1m[34mSELECT `schema_migrations`.* FROM `schema_migrations`[0m
  [1m[35m (0.5ms)[0m  [1m[35mSHOW CREATE TABLE `organizational_events`[0m
  [1m[35m (1.0ms)[0m  [1m[35mSHOW TABLE STATUS LIKE 'organizational_events'[0m
  [1m[35m (1.0ms)[0m  [1m[35mSHOW CREATE TABLE `organizations`[0m
  [1m[35m (1.0ms)[0m  [1m[35mSHOW TABLE STATUS LIKE 'organizations'[0m
Started POST "/api/v1/organizations" for ::1 at 2019-03-21 21:12:48 -0700
  [1m[36mActiveRecord::SchemaMigration Load (1.0ms)[0m  [1m[34mSELECT `schema_migrations`.* FROM `schema_migrations`[0m
  
SyntaxError (C:/Sites/OrganizationalEvents/app/controllers/api/v1/organizations_controller.rb:3: class/module name must be CONSTANT
    class organizationsController < ApplicationController
                                   ^):
  
app/controllers/api/v1/organizations_controller.rb:3: class/module name must be CONSTANT
Started POST "/api/v1/organizations" for ::1 at 2019-03-21 21:15:22 -0700
  
SyntaxError (C:/Sites/OrganizationalEvents/app/controllers/api/v1/organizations_controller.rb:3: class/module name must be CONSTANT
    class organizationsController < ApplicationController
                                   ^):
  
app/controllers/api/v1/organizations_controller.rb:3: class/module name must be CONSTANT
Started POST "/api/v1/organizations" for ::1 at 2019-03-21 21:17:32 -0700
Processing by Api::V1::OrganizationsController#create as */*
  Parameters: {"orgname"=>"Nutanix", "country"=>"US", "state"=>"CA", "city"=>"San Jose", "street"=>"Technology drive", "organization"=>{"orgname"=>"Nutanix", "country"=>"US", "state"=>"CA", "city"=>"San Jose", "street"=>"Technology drive"}}
Unpermitted parameter: organization
  [1m[35m (0.0ms)[0m  [1m[35mBEGIN[0m
  [1m[35mSQL (2.5ms)[0m  [1m[32mINSERT INTO `organizations` (`orgname`, `country`, `state`, `city`, `street`, `created_at`, `updated_at`) VALUES ('Nutanix', 'US', 'CA', 'San Jose', 'Technology drive', '2019-03-22 04:17:33', '2019-03-22 04:17:33')[0m
  [1m[35m (1.0ms)[0m  [1m[35mCOMMIT[0m
Completed 200 OK in 79ms (Views: 2.4ms | ActiveRecord: 8.9ms)


Started GET "/api/v1/organizations" for ::1 at 2019-03-21 21:19:44 -0700
  
AbstractController::ActionNotFound (The action 'index' could not be found for Api::V1::OrganizationsController):
  
actionpack (5.0.7.2) lib/abstract_controller/base.rb:121:in `process'
actionpack (5.0.7.2) lib/action_controller/metal.rb:190:in `dispatch'
actionpack (5.0.7.2) lib/action_controller/metal.rb:262:in `dispatch'
actionpack (5.0.7.2) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
actionpack (5.0.7.2) lib/action_dispatch/routing/route_set.rb:32:in `serve'
actionpack (5.0.7.2) lib/action_dispatch/journey/router.rb:39:in `block in serve'
actionpack (5.0.7.2) lib/action_dispatch/journey/router.rb:26:in `each'
actionpack (5.0.7.2) lib/action_dispatch/journey/router.rb:26:in `serve'
actionpack (5.0.7.2) lib/action_dispatch/routing/route_set.rb:727:in `call'
rack (2.0.6) lib/rack/etag.rb:25:in `call'
rack (2.0.6) lib/rack/conditional_get.rb:25:in `call'
rack (2.0.6) lib/rack/head.rb:12:in `call'
activerecord (5.0.7.2) lib/active_record/migration.rb:553:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:97:in `__run_callbacks__'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:90:in `run_callbacks'
actionpack (5.0.7.2) lib/action_dispatch/middleware/callbacks.rb:36:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.0.7.2) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.0.7.2) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.0.7.2) lib/rails/rack/logger.rb:24:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/request_id.rb:24:in `call'
rack (2.0.6) lib/rack/runtime.rb:22:in `call'
activesupport (5.0.7.2) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/static.rb:136:in `call'
rack (2.0.6) lib/rack/sendfile.rb:111:in `call'
railties (5.0.7.2) lib/rails/engine.rb:522:in `call'
puma (3.12.1) lib/puma/configuration.rb:227:in `call'
puma (3.12.1) lib/puma/server.rb:660:in `handle_request'
puma (3.12.1) lib/puma/server.rb:474:in `process_client'
puma (3.12.1) lib/puma/server.rb:334:in `block in run'
puma (3.12.1) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Started GET "/api/v1/organizations/1" for ::1 at 2019-03-21 21:19:57 -0700
Processing by Api::V1::OrganizationsController#show as */*
  Parameters: {"id"=>"1"}
  [1m[36mOrganization Load (0.5ms)[0m  [1m[34mSELECT  `organizations`.* FROM `organizations` WHERE `organizations`.`id` = 1 LIMIT 1[0m
Completed 200 OK in 10ms (Views: 0.7ms | ActiveRecord: 0.5ms)


Started GET "/api/v1/organizations" for ::1 at 2019-03-21 21:23:57 -0700
Processing by Api::V1::OrganizationsController#index as */*
  [1m[36mOrganization Load (0.5ms)[0m  [1m[34mSELECT `organizations`.* FROM `organizations` ORDER BY created_at DESC[0m
Completed 200 OK in 35ms (Views: 21.0ms | ActiveRecord: 0.5ms)


Started POST "/api/v1/organizations" for ::1 at 2019-03-21 21:30:33 -0700
Processing by Api::V1::OrganizationsController#create as */*
  Parameters: {"orgname"=>"ILLUMINA", "country"=>"US", "state"=>"CA", "city"=>"San Diego", "street"=>"Illumina Way", "organization"=>{"orgname"=>"ILLUMINA", "country"=>"US", "state"=>"CA", "city"=>"San Diego", "street"=>"Illumina Way"}}
Unpermitted parameter: organization
  [1m[35m (0.0ms)[0m  [1m[35mBEGIN[0m
  [1m[35mSQL (2.0ms)[0m  [1m[32mINSERT INTO `organizations` (`orgname`, `country`, `state`, `city`, `street`, `created_at`, `updated_at`) VALUES ('ILLUMINA', 'US', 'CA', 'San Diego', 'Illumina Way', '2019-03-22 04:30:33', '2019-03-22 04:30:33')[0m
  [1m[35m (1.0ms)[0m  [1m[35mCOMMIT[0m
Completed 200 OK in 29ms (Views: 1.2ms | ActiveRecord: 3.0ms)


Started GET "/api/v1/organizations" for ::1 at 2019-03-21 21:30:46 -0700
Processing by Api::V1::OrganizationsController#index as */*
  [1m[36mOrganization Load (1.5ms)[0m  [1m[34mSELECT `organizations`.* FROM `organizations` ORDER BY created_at DESC[0m
Completed 200 OK in 7ms (Views: 4.8ms | ActiveRecord: 1.5ms)


Started GET "/api/v1/organizations/ILLUMINA" for ::1 at 2019-03-21 21:32:24 -0700
Processing by Api::V1::OrganizationsController#show as */*
  Parameters: {"id"=>"ILLUMINA"}
  [1m[36mOrganization Load (1.0ms)[0m  [1m[34mSELECT  `organizations`.* FROM `organizations` WHERE `organizations`.`id` = NULL LIMIT 1[0m
Completed 404 Not Found in 30ms (ActiveRecord: 8.5ms)


  
ActiveRecord::RecordNotFound (Couldn't find Organization with 'id'=):
  
app/controllers/api/v1/organizations_controller.rb:12:in `show'
Started GET "/api/v1/organizations/ILLUMINA" for ::1 at 2019-03-21 21:46:26 -0700
Processing by Api::V1::OrganizationsController#show as */*
  Parameters: {"id"=>"ILLUMINA"}
Completed 500 Internal Server Error in 9ms (ActiveRecord: 0.0ms)


  
ArgumentError (wrong number of arguments (given 0, expected 1..2)):
  
app/controllers/api/v1/organizations_controller.rb:13:in `show'
Started GET "/api/v1/organizations/ILLUMINA" for ::1 at 2019-03-21 22:11:39 -0700
  
SyntaxError (C:/Sites/OrganizationalEvents/app/controllers/api/v1/organizations_controller.rb:13: unterminated string meets end of file
C:/Sites/OrganizationalEvents/app/controllers/api/v1/organizations_controller.rb:13: syntax error, unexpected end-of-input, expecting ']'):
  
app/controllers/api/v1/organizations_controller.rb:13: unterminated string meets end of file
app/controllers/api/v1/organizations_controller.rb:13: syntax error, unexpected end-of-input, expecting ']'
Started GET "/api/v1/organizations/ILLUMINA" for ::1 at 2019-03-21 22:12:17 -0700
Processing by Api::V1::OrganizationsController#show as */*
  Parameters: {"id"=>"ILLUMINA"}
Completed 500 Internal Server Error in 9ms (ActiveRecord: 0.0ms)


  
ArgumentError (wrong number of arguments (given 0, expected 1..2)):
  
app/controllers/api/v1/organizations_controller.rb:13:in `show'
Started GET "/api/v1/organizations/ILLUMINA" for ::1 at 2019-03-21 22:13:28 -0700
Processing by Api::V1::OrganizationsController#show as */*
  Parameters: {"id"=>"ILLUMINA"}
Completed 500 Internal Server Error in 9ms (ActiveRecord: 0.0ms)


  
ArgumentError (wrong number of arguments (given 0, expected 1..2)):
  
app/controllers/api/v1/organizations_controller.rb:13:in `show'
Started GET "/api/v1/organizations/ILLUMINA" for ::1 at 2019-03-21 22:14:47 -0700
Processing by Api::V1::OrganizationsController#show as */*
  Parameters: {"id"=>"ILLUMINA"}
Completed 500 Internal Server Error in 9ms (ActiveRecord: 0.0ms)


  
ArgumentError (wrong number of arguments (given 0, expected 1..2)):
  
app/controllers/api/v1/organizations_controller.rb:13:in `show'
Started GET "/api/v1/organizations" for ::1 at 2019-03-21 22:15:07 -0700
Processing by Api::V1::OrganizationsController#index as */*
  [1m[36mOrganization Load (1.5ms)[0m  [1m[34mSELECT `organizations`.* FROM `organizations` ORDER BY created_at DESC[0m
Completed 200 OK in 34ms (Views: 25.2ms | ActiveRecord: 7.5ms)


Started GET "/api/v1/organizations/" for ::1 at 2019-03-21 22:15:20 -0700
Processing by Api::V1::OrganizationsController#index as */*
  [1m[36mOrganization Load (0.5ms)[0m  [1m[34mSELECT `organizations`.* FROM `organizations` ORDER BY created_at DESC[0m
Completed 200 OK in 6ms (Views: 5.2ms | ActiveRecord: 0.5ms)


Started GET "/api/v1/organizations/1" for ::1 at 2019-03-21 22:15:27 -0700
Processing by Api::V1::OrganizationsController#show as */*
  Parameters: {"id"=>"1"}
Completed 500 Internal Server Error in 1ms (ActiveRecord: 0.0ms)


  
ArgumentError (wrong number of arguments (given 0, expected 1..2)):
  
app/controllers/api/v1/organizations_controller.rb:13:in `show'
Started GET "/api/v1/organizations" for ::1 at 2019-03-21 22:34:48 -0700
Processing by Api::V1::OrganizationsController#index as */*
  [1m[36mOrganization Load (1.0ms)[0m  [1m[34mSELECT `organizations`.* FROM `organizations` ORDER BY created_at DESC[0m
Completed 200 OK in 34ms (Views: 18.6ms | ActiveRecord: 5.5ms)


Started GET "/api/v1/organizations/1" for ::1 at 2019-03-21 22:34:54 -0700
Processing by Api::V1::OrganizationsController#show as */*
  Parameters: {"id"=>"1"}
Completed 500 Internal Server Error in 3ms (ActiveRecord: 0.0ms)


  
ArgumentError (wrong number of arguments (given 0, expected 1..2)):
  
app/controllers/api/v1/organizations_controller.rb:13:in `show'
Started GET "/api/v1/organizations/1" for ::1 at 2019-03-21 22:35:48 -0700
Processing by Api::V1::OrganizationsController#show as */*
  Parameters: {"id"=>"1"}
  [1m[36mOrganization Load (1.0ms)[0m  [1m[35m[0m
Completed 500 Internal Server Error in 14ms (ActiveRecord: 1.0ms)


  
ActiveRecord::StatementInvalid (TypeError: wrong argument type nil (expected String): ):
  
app/controllers/api/v1/organizations_controller.rb:12:in `show'
Started GET "/api/v1/organizations/ILLUMINA" for ::1 at 2019-03-21 22:35:56 -0700
Processing by Api::V1::OrganizationsController#show as */*
  Parameters: {"id"=>"ILLUMINA"}
  [1m[36mOrganization Load (0.5ms)[0m  [1m[35m[0m
Completed 500 Internal Server Error in 2ms (ActiveRecord: 0.5ms)


  
ActiveRecord::StatementInvalid (TypeError: wrong argument type nil (expected String): ):
  
app/controllers/api/v1/organizations_controller.rb:12:in `show'
Started GET "/api/v1/organizations/%22ILLUMINA%22" for ::1 at 2019-03-21 22:36:19 -0700
Processing by Api::V1::OrganizationsController#show as */*
  Parameters: {"id"=>"\"ILLUMINA\""}
  [1m[36mOrganization Load (1.0ms)[0m  [1m[35m[0m
Completed 500 Internal Server Error in 2ms (ActiveRecord: 1.0ms)


  
ActiveRecord::StatementInvalid (TypeError: wrong argument type nil (expected String): ):
  
app/controllers/api/v1/organizations_controller.rb:12:in `show'
Started GET "/api/v1/organizations/%7BILLUMINA%7D" for ::1 at 2019-03-21 22:36:31 -0700
Processing by Api::V1::OrganizationsController#show as */*
  Parameters: {"id"=>"{ILLUMINA}"}
  [1m[36mOrganization Load (0.5ms)[0m  [1m[35m[0m
Completed 500 Internal Server Error in 2ms (ActiveRecord: 0.5ms)


  
ActiveRecord::StatementInvalid (TypeError: wrong argument type nil (expected String): ):
  
app/controllers/api/v1/organizations_controller.rb:12:in `show'
Started GET "/api/v1/organizations?org_name=%27ILLUMINA%27" for ::1 at 2019-03-21 22:38:06 -0700
Processing by Api::V1::OrganizationsController#index as */*
  Parameters: {"org_name"=>"'ILLUMINA'"}
  [1m[36mOrganization Load (0.5ms)[0m  [1m[34mSELECT `organizations`.* FROM `organizations` ORDER BY created_at DESC[0m
Completed 200 OK in 34ms (Views: 20.7ms | ActiveRecord: 5.0ms)


Started GET "/api/v1/organizations?org_name=%27ILLUMINA%27" for ::1 at 2019-03-21 22:39:17 -0700
Processing by Api::V1::OrganizationsController#index as */*
  Parameters: {"org_name"=>"'ILLUMINA'"}
  [1m[36mOrganization Load (0.5ms)[0m  [1m[34mSELECT `organizations`.* FROM `organizations` ORDER BY created_at DESC[0m
Completed 200 OK in 28ms (Views: 17.4ms | ActiveRecord: 0.5ms)


Started GET "/api/v1/organizations?org_name=%22ILLUMINA%22" for ::1 at 2019-03-21 22:39:33 -0700
Processing by Api::V1::OrganizationsController#index as */*
  Parameters: {"org_name"=>"\"ILLUMINA\""}
  [1m[36mOrganization Load (1.0ms)[0m  [1m[34mSELECT `organizations`.* FROM `organizations` ORDER BY created_at DESC[0m
Completed 200 OK in 8ms (Views: 6.5ms | ActiveRecord: 1.0ms)


Started GET "/api/v1/organizations?org_name=%22ILLUMINA%22" for ::1 at 2019-03-21 22:40:36 -0700
Processing by Api::V1::OrganizationsController#index as */*
  Parameters: {"org_name"=>"\"ILLUMINA\""}
  [1m[36mOrganization Load (5.0ms)[0m  [1m[34mSELECT `organizations`.* FROM `organizations` ORDER BY created_at DESC[0m
Completed 200 OK in 66ms (Views: 31.3ms | ActiveRecord: 12.5ms)


Started GET "/api/v1/organizations?org_name=%22ILLUMINA%22" for ::1 at 2019-03-21 22:41:00 -0700
Processing by Api::V1::OrganizationsController#index as */*
  Parameters: {"org_name"=>"\"ILLUMINA\""}
  [1m[36mOrganization Load (0.5ms)[0m  [1m[34mSELECT `organizations`.* FROM `organizations` ORDER BY created_at DESC[0m
Completed 200 OK in 35ms (Views: 21.7ms | ActiveRecord: 0.5ms)


Started GET "/api/v1/organizations/1" for ::1 at 2019-03-21 22:41:40 -0700
Processing by Api::V1::OrganizationsController#show as */*
  Parameters: {"id"=>"1"}
  [1m[36mOrganization Load (0.5ms)[0m  [1m[34mSELECT  `organizations`.* FROM `organizations` WHERE `organizations`.`id` = 1 LIMIT 1[0m
Completed 200 OK in 31ms (Views: 0.9ms | ActiveRecord: 0.5ms)


Started GET "/api/v1/organizations/2" for ::1 at 2019-03-21 22:41:48 -0700
Processing by Api::V1::OrganizationsController#show as */*
  Parameters: {"id"=>"2"}
  [1m[36mOrganization Load (0.5ms)[0m  [1m[34mSELECT  `organizations`.* FROM `organizations` WHERE `organizations`.`id` = 2 LIMIT 1[0m
Completed 200 OK in 3ms (Views: 0.9ms | ActiveRecord: 0.5ms)


Started GET "/api/v1/organizations/ILLUMINA" for ::1 at 2019-03-21 22:42:03 -0700
Processing by Api::V1::OrganizationsController#show as */*
  Parameters: {"id"=>"ILLUMINA"}
  [1m[36mOrganization Load (0.5ms)[0m  [1m[34mSELECT  `organizations`.* FROM `organizations` WHERE `organizations`.`id` = 0 LIMIT 1[0m
Completed 404 Not Found in 2ms (ActiveRecord: 0.5ms)


  
ActiveRecord::RecordNotFound (Couldn't find Organization with 'id'=ILLUMINA):
  
app/controllers/api/v1/organizations_controller.rb:12:in `show'
Started GET "/api/v1/organizations/ILLUMINA" for ::1 at 2019-03-21 22:43:04 -0700
Processing by Api::V1::OrganizationsController#show as */*
  Parameters: {"id"=>"ILLUMINA"}
  [1m[36mOrganization Load (0.5ms)[0m  [1m[34mSELECT  `organizations`.* FROM `organizations` WHERE `organizations`.`id` = NULL LIMIT 1[0m
Completed 404 Not Found in 9ms (ActiveRecord: 0.5ms)


  
ActiveRecord::RecordNotFound (Couldn't find Organization with 'id'=):
  
app/controllers/api/v1/organizations_controller.rb:12:in `show'
Started GET "/api/v1/organizations/ILLUMINA" for ::1 at 2019-03-21 22:43:31 -0700
Processing by Api::V1::OrganizationsController#show as */*
  Parameters: {"id"=>"ILLUMINA"}
  [1m[36mOrganization Load (1.0ms)[0m  [1m[34mSELECT  `organizations`.* FROM `organizations` WHERE `organizations`.`id` = NULL LIMIT 1[0m
Completed 404 Not Found in 13ms (ActiveRecord: 1.0ms)


  
ActiveRecord::RecordNotFound (Couldn't find Organization with 'id'=):
  
app/controllers/api/v1/organizations_controller.rb:12:in `show'
Started GET "/api/v1/organizationsbyname/ILLUMINA" for ::1 at 2019-03-21 22:48:12 -0700
  
ActionController::RoutingError (uninitialized constant Api::V1::OrganizationsbynameController):
  
activesupport (5.0.7.2) lib/active_support/inflector/methods.rb:270:in `const_get'
activesupport (5.0.7.2) lib/active_support/inflector/methods.rb:270:in `block in constantize'
activesupport (5.0.7.2) lib/active_support/inflector/methods.rb:266:in `each'
activesupport (5.0.7.2) lib/active_support/inflector/methods.rb:266:in `inject'
activesupport (5.0.7.2) lib/active_support/inflector/methods.rb:266:in `constantize'
actionpack (5.0.7.2) lib/action_dispatch/http/request.rb:81:in `controller_class'
actionpack (5.0.7.2) lib/action_dispatch/routing/route_set.rb:44:in `controller'
actionpack (5.0.7.2) lib/action_dispatch/routing/route_set.rb:30:in `serve'
actionpack (5.0.7.2) lib/action_dispatch/journey/router.rb:39:in `block in serve'
actionpack (5.0.7.2) lib/action_dispatch/journey/router.rb:26:in `each'
actionpack (5.0.7.2) lib/action_dispatch/journey/router.rb:26:in `serve'
actionpack (5.0.7.2) lib/action_dispatch/routing/route_set.rb:727:in `call'
rack (2.0.6) lib/rack/etag.rb:25:in `call'
rack (2.0.6) lib/rack/conditional_get.rb:25:in `call'
rack (2.0.6) lib/rack/head.rb:12:in `call'
activerecord (5.0.7.2) lib/active_record/migration.rb:553:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:97:in `__run_callbacks__'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:90:in `run_callbacks'
actionpack (5.0.7.2) lib/action_dispatch/middleware/callbacks.rb:36:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.0.7.2) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.0.7.2) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.0.7.2) lib/rails/rack/logger.rb:24:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/request_id.rb:24:in `call'
rack (2.0.6) lib/rack/runtime.rb:22:in `call'
activesupport (5.0.7.2) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/static.rb:136:in `call'
rack (2.0.6) lib/rack/sendfile.rb:111:in `call'
railties (5.0.7.2) lib/rails/engine.rb:522:in `call'
puma (3.12.1) lib/puma/configuration.rb:227:in `call'
puma (3.12.1) lib/puma/server.rb:660:in `handle_request'
puma (3.12.1) lib/puma/server.rb:474:in `process_client'
puma (3.12.1) lib/puma/server.rb:334:in `block in run'
puma (3.12.1) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Started GET "/api/v1/organizations/ILLUMINA" for ::1 at 2019-03-21 22:59:23 -0700
Processing by Api::V1::OrganizationsController#show as */*
  Parameters: {"id"=>"ILLUMINA"}
  [1m[36mOrganization Load (6.5ms)[0m  [1m[34mSELECT  `organizations`.* FROM `organizations` WHERE `organizations`.`orgname` IS NULL LIMIT 1[0m
Completed 200 OK in 40ms (Views: 0.4ms | ActiveRecord: 6.5ms)


Started GET "/api/v1/organizations/Nutanix" for ::1 at 2019-03-21 23:00:44 -0700
Processing by Api::V1::OrganizationsController#show as */*
  Parameters: {"id"=>"Nutanix"}
  [1m[36mOrganization Load (1.0ms)[0m  [1m[34mSELECT  `organizations`.* FROM `organizations` WHERE `organizations`.`orgname` IS NULL LIMIT 1[0m
Completed 200 OK in 5ms (Views: 0.3ms | ActiveRecord: 1.0ms)


Started GET "/api/v1/organizations/1" for ::1 at 2019-03-21 23:00:54 -0700
Processing by Api::V1::OrganizationsController#show as */*
  Parameters: {"id"=>"1"}
  [1m[36mOrganization Load (1.0ms)[0m  [1m[34mSELECT  `organizations`.* FROM `organizations` WHERE `organizations`.`orgname` IS NULL LIMIT 1[0m
Completed 200 OK in 3ms (Views: 0.2ms | ActiveRecord: 1.0ms)


Started GET "/api/v1/organizations/1" for ::1 at 2019-03-21 23:07:23 -0700
Processing by Api::V1::OrganizationsController#show as */*
  Parameters: {"id"=>"1"}
  [1m[36mOrganization Load (0.5ms)[0m  [1m[34mSELECT  `organizations`.* FROM `organizations` WHERE `organizations`.`id` = NULL LIMIT 1[0m
Completed 404 Not Found in 16ms (ActiveRecord: 0.5ms)


  
ActiveRecord::RecordNotFound (Couldn't find Organization with 'id'=):
  
app/controllers/api/v1/organizations_controller.rb:12:in `show'
Started GET "/api/v1/organizations/ILLUMINA" for ::1 at 2019-03-21 23:07:31 -0700
Processing by Api::V1::OrganizationsController#show as */*
  Parameters: {"id"=>"ILLUMINA"}
  [1m[36mOrganization Load (0.5ms)[0m  [1m[34mSELECT  `organizations`.* FROM `organizations` WHERE `organizations`.`id` = NULL LIMIT 1[0m
Completed 404 Not Found in 3ms (ActiveRecord: 0.5ms)


  
ActiveRecord::RecordNotFound (Couldn't find Organization with 'id'=):
  
app/controllers/api/v1/organizations_controller.rb:12:in `show'
Started GET "/api/v1/organizations/ILLUMINA" for ::1 at 2019-03-21 23:08:24 -0700
Processing by Api::V1::OrganizationsController#show as */*
  Parameters: {"id"=>"ILLUMINA"}
  [1m[36mOrganization Load (0.5ms)[0m  [1m[34mSELECT  `organizations`.* FROM `organizations` WHERE `organizations`.`orgname` IS NULL LIMIT 1[0m
Completed 200 OK in 43ms (Views: 0.3ms | ActiveRecord: 5.0ms)


Started GET "/api/v1/organizations/ILLUMINA" for ::1 at 2019-03-21 23:09:03 -0700
Processing by Api::V1::OrganizationsController#show as */*
  Parameters: {"id"=>"ILLUMINA"}
  [1m[36mOrganization Load (0.5ms)[0m  [1m[34mSELECT  `organizations`.* FROM `organizations` WHERE `organizations`.`orgname` IS NULL LIMIT 1[0m
Completed 200 OK in 16ms (Views: 0.2ms | ActiveRecord: 0.5ms)


Started GET "/api/v1/organizations/ILLUMINA" for ::1 at 2019-03-21 23:10:07 -0700
Processing by Api::V1::OrganizationsController#show as */*
  Parameters: {"id"=>"ILLUMINA"}
  [1m[36mOrganization Load (0.5ms)[0m  [1m[34mSELECT  `organizations`.* FROM `organizations` WHERE `organizations`.`orgname` IS NULL LIMIT 1[0m
Completed 200 OK in 16ms (Views: 0.5ms | ActiveRecord: 0.5ms)


Started GET "/api/v1/organizations/ILLUMINA" for ::1 at 2019-03-21 23:10:32 -0700
Processing by Api::V1::OrganizationsController#show as */*
  Parameters: {"id"=>"ILLUMINA"}
  [1m[36mOrganization Load (1.0ms)[0m  [1m[34mSELECT  `organizations`.* FROM `organizations` WHERE `organizations`.`orgname` IS NULL LIMIT 1[0m
Completed 200 OK in 24ms (Views: 2.8ms | ActiveRecord: 1.0ms)


Started GET "/api/v1/organizations/ILLUMINA" for ::1 at 2019-03-21 23:23:31 -0700
Processing by Api::V1::OrganizationsController#show as */*
  Parameters: {"id"=>"ILLUMINA"}
  [1m[36mOrganization Load (0.5ms)[0m  [1m[34mSELECT  `organizations`.* FROM `organizations` WHERE `organizations`.`orgname` IS NULL LIMIT 1[0m
Completed 200 OK in 22ms (Views: 0.4ms | ActiveRecord: 0.5ms)


Started GET "/api/v1/organizations/ILLUMINA" for ::1 at 2019-03-21 23:24:18 -0700
  
AbstractController::ActionNotFound (The action 'show' could not be found for Api::V1::OrganizationsController):
  
actionpack (5.0.7.2) lib/abstract_controller/base.rb:121:in `process'
actionpack (5.0.7.2) lib/action_controller/metal.rb:190:in `dispatch'
actionpack (5.0.7.2) lib/action_controller/metal.rb:262:in `dispatch'
actionpack (5.0.7.2) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
actionpack (5.0.7.2) lib/action_dispatch/routing/route_set.rb:32:in `serve'
actionpack (5.0.7.2) lib/action_dispatch/journey/router.rb:39:in `block in serve'
actionpack (5.0.7.2) lib/action_dispatch/journey/router.rb:26:in `each'
actionpack (5.0.7.2) lib/action_dispatch/journey/router.rb:26:in `serve'
actionpack (5.0.7.2) lib/action_dispatch/routing/route_set.rb:727:in `call'
rack (2.0.6) lib/rack/etag.rb:25:in `call'
rack (2.0.6) lib/rack/conditional_get.rb:25:in `call'
rack (2.0.6) lib/rack/head.rb:12:in `call'
activerecord (5.0.7.2) lib/active_record/migration.rb:553:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:97:in `__run_callbacks__'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:90:in `run_callbacks'
actionpack (5.0.7.2) lib/action_dispatch/middleware/callbacks.rb:36:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.0.7.2) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.0.7.2) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.0.7.2) lib/rails/rack/logger.rb:24:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/request_id.rb:24:in `call'
rack (2.0.6) lib/rack/runtime.rb:22:in `call'
activesupport (5.0.7.2) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/static.rb:136:in `call'
rack (2.0.6) lib/rack/sendfile.rb:111:in `call'
railties (5.0.7.2) lib/rails/engine.rb:522:in `call'
puma (3.12.1) lib/puma/configuration.rb:227:in `call'
puma (3.12.1) lib/puma/server.rb:660:in `handle_request'
puma (3.12.1) lib/puma/server.rb:474:in `process_client'
puma (3.12.1) lib/puma/server.rb:334:in `block in run'
puma (3.12.1) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Started GET "/api/v1/organizations/ILLUMINA" for ::1 at 2019-03-21 23:25:07 -0700
Processing by Api::V1::OrganizationsController#show as */*
  Parameters: {"id"=>"ILLUMINA"}
  [1m[36mOrganization Load (0.5ms)[0m  [1m[34mSELECT  `organizations`.* FROM `organizations` WHERE `organizations`.`id` = NULL LIMIT 1[0m
Completed 404 Not Found in 12ms (ActiveRecord: 2.0ms)


  
ActiveRecord::RecordNotFound (Couldn't find Organization with 'id'=):
  
app/controllers/api/v1/organizations_controller.rb:10:in `show'
Started GET "/api/v1/organizations/ILLUMINA" for ::1 at 2019-03-21 23:25:41 -0700
Processing by Api::V1::OrganizationsController#show as */*
  Parameters: {"id"=>"ILLUMINA"}
  [1m[36mOrganization Load (0.5ms)[0m  [1m[34mSELECT  `organizations`.* FROM `organizations` WHERE `organizations`.`orgname` IS NULL LIMIT 1[0m
Completed 200 OK in 12ms (Views: 0.4ms | ActiveRecord: 0.5ms)


Started GET "/api/v1/organizations/ILLUMINA" for ::1 at 2019-03-21 23:26:19 -0700
Processing by Api::V1::OrganizationsController#show as */*
  Parameters: {"id"=>"ILLUMINA"}
  [1m[36mOrganization Load (1.5ms)[0m  [1m[34mSELECT  `organizations`.* FROM `organizations` WHERE `organizations`.`orgname` = 'ILLUMINA' LIMIT 1[0m
Completed 200 OK in 86ms (Views: 56.7ms | ActiveRecord: 1.5ms)


